-- =====================================================================
-- V10 (P2-admin 18a):管理站账号认证 + 审计检索支撑
-- 依据:02-技术方案 §6.3(管理站人类管理员认证:内置管理员账号,
--       Argon2 口令散列 + 失败锁定 + 登录审计);03-开发计划 W5。
-- 内容:
--   * ia_admin_account:内置管理员账号表(username 唯一 / Argon2 哈希 /
--     失败锁定 / 状态)
--   * ia_admin_login_log:登录审计(独立表,与 ia_audit_log 工具审计分域;
--     技术方案未定独立表还是扩展,自拟独立表——登录事件与工具决策
--     生命周期/字段形完全不同,分表避免 ia_audit_log 值域被稀释)
--   * ia_audit_log 检索索引增补(W5 审计检索:decision_source 过滤、
--     工具名过滤走索引)
-- 平台级表说明:两表为「管理面」平台级单例域(管理员跨应用),实体上仍
-- 遵守迁移规范携带 app_id/tenant_id(默认 1/0),但加入
-- AppTenantLineInnerInterceptor.IGNORED_TABLES 不参与行级注入——
-- 管理员账号按 username 全局定位,与 AppContext 无关。
-- Argon2 参数(P2 定档,spring-security Argon2PasswordEncoder
-- defaultsForSpringSecurity_v5_8 等价):
--   saltLength=16, hashLength=32, parallelism=1, memory=16384 KiB(16 MiB),
--   iterations=2 → 形如 $argon2id$v=19$m=16384,t=2,p=1$<salt>$<hash>;
--   存储列 password_hash VARCHAR(256) 足容。
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. ia_admin_account:内置管理员账号表(新增;引导账号由
--    IA_ADMIN_BOOTSTRAP_PASSWORD 在启动时创建,见 AdminAuthService)
-- ---------------------------------------------------------------------
CREATE TABLE ia_admin_account (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id          BIGINT       NOT NULL DEFAULT 1,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    username        VARCHAR(64)  NOT NULL,
    password_hash   VARCHAR(256) NOT NULL,
    failed_attempts INT          NOT NULL DEFAULT 0,
    locked_until    TIMESTAMP,
    status          INT          NOT NULL DEFAULT 1,
    last_login_at   TIMESTAMP,
    remark          VARCHAR(255),
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ia_admin_account_username UNIQUE (username)
);

COMMENT ON TABLE ia_admin_account IS '管理站内置管理员账号表(02-技术方案 §6.3;Argon2 口令散列)';
COMMENT ON COLUMN ia_admin_account.id IS '主键ID';
COMMENT ON COLUMN ia_admin_account.app_id IS '所属应用;管理员为平台级账号,单应用部署固定为 1(迁移规范强制携带)';
COMMENT ON COLUMN ia_admin_account.tenant_id IS '所属租户(团队)ID;平台级账号固定 0';
COMMENT ON COLUMN ia_admin_account.username IS '登录用户名(全局唯一)';
COMMENT ON COLUMN ia_admin_account.password_hash IS 'Argon2id 口令散列($argon2id$v=19$m=16384,t=2,p=1$…,spring-security Argon2PasswordEncoder 编码,含盐自校验)';
COMMENT ON COLUMN ia_admin_account.failed_attempts IS '连续登录失败次数(成功登录清零;达到阈值触发锁定)';
COMMENT ON COLUMN ia_admin_account.locked_until IS '锁定截止时间(NULL=未锁定;超过阈值后 now+15min,可配)';
COMMENT ON COLUMN ia_admin_account.status IS '账号状态:1-启用 0-停用';
COMMENT ON COLUMN ia_admin_account.last_login_at IS '最近一次成功登录时间';
COMMENT ON COLUMN ia_admin_account.remark IS '备注';
COMMENT ON COLUMN ia_admin_account.create_time IS '创建时间';
COMMENT ON COLUMN ia_admin_account.update_time IS '更新时间';

-- ---------------------------------------------------------------------
-- 2. ia_admin_login_log:管理员登录审计(新增;全部尝试落库,含成功)
-- ---------------------------------------------------------------------
CREATE TABLE ia_admin_login_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id      BIGINT       NOT NULL DEFAULT 1,
    tenant_id   BIGINT       NOT NULL DEFAULT 0,
    username    VARCHAR(64)  NOT NULL,
    ip          VARCHAR(64),
    success     BOOLEAN      NOT NULL,
    fail_reason VARCHAR(255),
    create_time TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ia_admin_login_log IS '管理员登录审计表(全部登录尝试追加,含成功;仅追加,不提供更新/删除)';
COMMENT ON COLUMN ia_admin_login_log.id IS '主键ID';
COMMENT ON COLUMN ia_admin_login_log.app_id IS '所属应用;平台级审计,单应用部署固定为 1';
COMMENT ON COLUMN ia_admin_login_log.tenant_id IS '所属租户(团队)ID;平台级审计固定 0';
COMMENT ON COLUMN ia_admin_login_log.username IS '尝试登录的用户名(原样记录,含不存在的账号)';
COMMENT ON COLUMN ia_admin_login_log.ip IS '发起方 IP(X-Forwarded-For 首值,缺省 remoteAddr)';
COMMENT ON COLUMN ia_admin_login_log.success IS '是否登录成功';
COMMENT ON COLUMN ia_admin_login_log.fail_reason IS '失败原因(账号不存在/密码错误/已锁定/已停用;成功为 NULL)';
COMMENT ON COLUMN ia_admin_login_log.create_time IS '创建时间(append-only,无更新/删除)';

CREATE INDEX idx_ia_admin_login_log_username_time
    ON ia_admin_login_log (username, create_time);

-- ---------------------------------------------------------------------
-- 3. ia_audit_log 检索索引增补(W5 审计检索;已有 (app_id, create_time) /
--    (app_id, conversation_id) / (app_id, run_id))
-- ---------------------------------------------------------------------
-- W5 计划硬性「审计检索[decision_source 过滤]」:来源过滤 + 时间排序走索引
CREATE INDEX idx_ia_audit_log_app_source_time
    ON ia_audit_log (app_id, decision_source, create_time);
-- 按工具 FQN 检索(工具名前缀 LIKE 由 PG 计划器回退全索引扫描,等值场景走本索引)
CREATE INDEX idx_ia_audit_log_app_tool
    ON ia_audit_log (app_id, tool_fqn);
