-- =====================================================================
-- InnerAgent V11:终态 Webhook 投递记录(任务 #18b,W5;PRD §6 终态通知、
-- 02-技术方案 §7.1「POST {宿主 webhook}:HMAC 签名,5 次指数退避重试」)
-- 设计要点:
--   * 事件源 = 运行终态(PRD 最小必要集):run.finished / run.failed /
--     run.cancelled,由 RunTerminalCoordinator 终态提交后异步落本表。
--   * 签名:HMAC-SHA256(secret, timestamp + "." + nonce + "." + body),
--     secret 取 ia_app.webhook_secret;每次投递尝试重算(时间戳新鲜,
--     宿主可做防重放窗口校验),signature 列保存最近一次尝试的签名。
--   * 重试:指数退避(默认 1m/5m/30m/2h/12h,5 次上限,可配
--     inneragent.webhook.*),经调度器领取(SKIP LOCKED + claim 租约,
--     与内核 outbox 同思路,多实例不重投);超过上限落 EXHAUSTED 可查,
--     支持管理端手动 redeliver。
--   * 迁移号 V11:主线任务 #18a 并行占用 V10,合并时由主线裁决编号。
-- =====================================================================

CREATE TABLE ia_webhook_delivery (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id           BIGINT       NOT NULL DEFAULT 1,
    event_type       VARCHAR(64)  NOT NULL,
    run_id           VARCHAR(64)  NOT NULL,
    url              VARCHAR(2048) NOT NULL,
    payload_json     TEXT         NOT NULL,
    signature        VARCHAR(256),
    status           VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    attempt_count    INT          NOT NULL DEFAULT 0,
    max_attempts     INT          NOT NULL DEFAULT 5,
    next_retry_at    TIMESTAMP(3),
    last_http_status INT,
    last_response    VARCHAR(1024),
    delivered_at     TIMESTAMP(3),
    claim_owner      VARCHAR(128),
    claim_until      TIMESTAMP(3),
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    create_time      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_ia_webhook_delivery_status
        CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'EXHAUSTED'))
);

COMMENT ON TABLE ia_webhook_delivery IS '终态 Webhook 投递记录(签名+重试;任务 #18b)';
COMMENT ON COLUMN ia_webhook_delivery.id IS '主键ID(亦作 X-IA-Delivery 投递头)';
COMMENT ON COLUMN ia_webhook_delivery.app_id IS '所属应用(ia_app.id;回调配置取该行 webhook_url/webhook_secret)';
COMMENT ON COLUMN ia_webhook_delivery.event_type IS '事件类型:run.finished/run.failed/run.cancelled';
COMMENT ON COLUMN ia_webhook_delivery.run_id IS '关联运行 ID';
COMMENT ON COLUMN ia_webhook_delivery.url IS '回调地址(入队时快照;每次尝试以 ia_app 当前配置为准)';
COMMENT ON COLUMN ia_webhook_delivery.payload_json IS '请求体 JSON(入队时冻结;时间戳/nonce 不入体,走签名头)';
COMMENT ON COLUMN ia_webhook_delivery.signature IS '最近一次尝试的 HMAC-SHA256 签名(hex;对 timestamp.nonce.body)';
COMMENT ON COLUMN ia_webhook_delivery.status IS '状态:PENDING-待投递/FAILED-失败待重试/SUCCESS-已投递/EXHAUSTED-重试耗尽';
COMMENT ON COLUMN ia_webhook_delivery.attempt_count IS '已尝试次数(领取时预增)';
COMMENT ON COLUMN ia_webhook_delivery.max_attempts IS '最大尝试次数(入队时按配置快照)';
COMMENT ON COLUMN ia_webhook_delivery.next_retry_at IS '下次可投递时间(NULL 表示立即可投)';
COMMENT ON COLUMN ia_webhook_delivery.last_http_status IS '最近一次尝试的 HTTP 状态码(传输异常为 NULL)';
COMMENT ON COLUMN ia_webhook_delivery.last_response IS '最近一次尝试的响应摘要(脱敏截断,≤1024)';
COMMENT ON COLUMN ia_webhook_delivery.delivered_at IS '首次投递成功时间';
COMMENT ON COLUMN ia_webhook_delivery.claim_owner IS '投递租约持有者(实例+令牌;多实例互斥)';
COMMENT ON COLUMN ia_webhook_delivery.claim_until IS '投递租约到期时间(过期可被其他实例接管)';
COMMENT ON COLUMN ia_webhook_delivery.deleted IS '逻辑删除标志';
COMMENT ON COLUMN ia_webhook_delivery.create_time IS '创建时间';
COMMENT ON COLUMN ia_webhook_delivery.update_time IS '更新时间';

-- 调度器领取扫描:按到期时间取待投/待重试行
CREATE INDEX idx_webhook_delivery_claim ON ia_webhook_delivery (status, next_retry_at);
-- 管理端检索:按应用过滤 + 稳定排序
CREATE INDEX idx_webhook_delivery_app ON ia_webhook_delivery (app_id, id);
