-- =====================================================================
-- InnerAgent V14:熔断与资源上限(优化建议 #2 服务端半)+ Webhook 订阅配置
--
-- 背景:web 管理站熔断/Webhook 两域此前仅有 mock 后端(handlers.ts 为产品
-- 契约锚点);服务端补齐「紧急停用最小实现」:
--   * ia_app 新列:limits 配置(JSON,§4.7 默认值)+ 应用级总开关三列 +
--     Webhook 订阅两列(enabled/events;url/secret 列 V2 已有)。
--   * ia_circuit_event 新表:紧急停用/恢复/单运行终止事件流水(GET 状态端点
--     recentEvents 数据源,mock 形 {id,type,runId,reason,operator,occurredAt})。
--
-- 边界说明:limits 中 mcpConcurrency/mcpQps 等「执行层上限」本版仅落库与
-- 管理面读写,内核目录/策略层暂无挂点,执行接线待后续(不强行重构内核);
-- 总开关(circuit_stopped)在 run 发起入口实时校验,停用后新 run 403。
--
-- 默认值来源:《02-技术方案》§4.7(单宿主 MCP 并发 8/QPS 20、确认超时 24h、
-- 单运行 30m)与 web 契约 ResourceLimits seed(32 次工具调用/300k token/
-- 重试 2 次)。
-- =====================================================================

-- 1. ia_app:熔断配置与应用级总开关 + Webhook 订阅
ALTER TABLE ia_app ADD COLUMN circuit_limits_json JSONB NOT NULL DEFAULT
    '{"maxToolCallsPerRun":32,"maxTokensPerRun":300000,"maxRunDurationMinutes":30,
      "toolRetryLimit":2,"mcpConcurrency":8,"mcpQps":20,"confirmTimeoutHours":24}'::jsonb;
ALTER TABLE ia_app ADD COLUMN circuit_stopped    BOOLEAN      NOT NULL DEFAULT FALSE;
ALTER TABLE ia_app ADD COLUMN circuit_stopped_at TIMESTAMP(3);
ALTER TABLE ia_app ADD COLUMN circuit_stop_reason VARCHAR(512);
ALTER TABLE ia_app ADD COLUMN webhook_enabled    BOOLEAN      NOT NULL DEFAULT TRUE;
ALTER TABLE ia_app ADD COLUMN webhook_events     VARCHAR(255) NOT NULL DEFAULT 'run.finished,run.failed,run.cancelled';

COMMENT ON COLUMN ia_app.circuit_limits_json IS '熔断资源上限配置 JSON(§4.7 默认;执行层接线待后续)';
COMMENT ON COLUMN ia_app.circuit_stopped IS '应用级紧急停用总开关(TRUE 时新 run 拒绝 403;进行中 run 需管理员逐个 terminate-run)';
COMMENT ON COLUMN ia_app.circuit_stopped_at IS '紧急停用时刻(恢复时清空)';
COMMENT ON COLUMN ia_app.circuit_stop_reason IS '紧急停用原因(恢复时清空)';
COMMENT ON COLUMN ia_app.webhook_enabled IS '终态 Webhook 投递总开关(FALSE 时终态事件不入队)';
COMMENT ON COLUMN ia_app.webhook_events IS 'Webhook 订阅事件(逗号分隔;run.finished/failed/cancelled/resource-limit)';

-- 2. ia_circuit_event:熔断事件流水(仅追加;mock 契约 CircuitBreakerEvent 形)
CREATE TABLE ia_circuit_event (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id      BIGINT       NOT NULL DEFAULT 1,
    tenant_id   BIGINT       NOT NULL DEFAULT 0,
    type        VARCHAR(32)  NOT NULL,
    run_id      VARCHAR(64),
    reason      VARCHAR(512),
    operator    VARCHAR(64)  NOT NULL DEFAULT 'admin',
    create_time TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ia_circuit_event IS '熔断事件流水(紧急停用/恢复/单运行终止/上限触发;仅追加)';
COMMENT ON COLUMN ia_circuit_event.id IS '主键ID(web 契约 CircuitBreakerEvent.id)';
COMMENT ON COLUMN ia_circuit_event.app_id IS '所属应用;单应用部署固定为 1,行级拦截器显式注入';
COMMENT ON COLUMN ia_circuit_event.tenant_id IS '所属租户(团队)ID';
COMMENT ON COLUMN ia_circuit_event.type IS '事件类型:emergency-stop/resume/run-terminated/limit-triggered';
COMMENT ON COLUMN ia_circuit_event.run_id IS '关联运行ID(应用级事件为 NULL)';
COMMENT ON COLUMN ia_circuit_event.reason IS '事件原因(停用/终止缘由;恢复固定「人工恢复」)';
COMMENT ON COLUMN ia_circuit_event.operator IS '操作者(管理会话用户名或 admin 引导通道)';
COMMENT ON COLUMN ia_circuit_event.create_time IS '发生时刻(web 契约 occurredAt,ISO-8601 序列化)';

CREATE INDEX idx_ia_circuit_event_app_time
    ON ia_circuit_event (app_id, create_time DESC);
