-- =====================================================================
-- InnerAgent V18 (P4-W13):三方 MCP 服务器注册(应用级 + 用户级)
--
-- PRD M2「三方 MCP」(03-开发计划 §7.1 W13):工具三来源之「三方工具」
-- (CRM/工单等跨应用 MCP),应用级由管理面注册、用户级由用户在会话/设置域
-- 自接;工具清单经 McpThirdPartyToolListCache(LRU)聚入 McpToolCatalog,
-- 聚合顺序 宿主 → 应用级三方 → 用户级三方 → 内置。
--
-- 表:
--   ia_mcp_server_config  应用级三方 MCP 服务器(管理面 /ia/api/v1/admin/mcp-servers)
--   ia_mcp_user_server    用户级三方 MCP 服务器(用户面 /ia/api/v1/mcp-servers,
--                         行级 userId 隔离——他人不可见)
--
-- 鉴权(02-技术方案 §6.1):三方服务器一律走规范 OAuth(CIMD/DCR + RFC 8707)
-- 或用户配置静态头;act token(X-IA-Act)仅限宿主桥内环,不发给三方。
-- 本轮(P4-W13)只落鉴权策略枚举位 STATIC_HEADER/OAUTH:OAUTH 配置即报 501
-- (流程 P4 后续批次实现)。静态头值落 credentials(TEXT;加密存储可延后),
-- 值不进审计/日志。
--
-- 教训落档(DEF-08,同 V15/V17):无 JSONB 列;后续扩展字段(JSON 形)一律
-- TEXT + 服务层序列化。
-- 仅增表,无数据变更。
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. ia_mcp_server_config:应用级三方 MCP 服务器(管理面维护)
-- ---------------------------------------------------------------------
CREATE TABLE ia_mcp_server_config (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id          BIGINT       NOT NULL DEFAULT 1,
    server_key      VARCHAR(64)  NOT NULL,
    name            VARCHAR(128) NOT NULL,
    endpoint_url    VARCHAR(2048) NOT NULL,
    transport       VARCHAR(32)  NOT NULL DEFAULT 'streamable-http',
    auth_type       VARCHAR(32)  NOT NULL DEFAULT 'STATIC_HEADER',
    header_name     VARCHAR(128),
    credentials     TEXT,
    timeout_seconds INT          NOT NULL DEFAULT 30,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ia_mcp_server_config_key UNIQUE (app_id, server_key)
);

COMMENT ON TABLE ia_mcp_server_config IS
    '应用级三方 MCP 服务器配置(管理面注册;工具清单 LRU 缓存后聚入 McpToolCatalog)';
COMMENT ON COLUMN ia_mcp_server_config.app_id IS '所属应用;单应用部署固定为 1';
COMMENT ON COLUMN ia_mcp_server_config.server_key IS
    '服务器键(FQN 命名空间 mcp__<serverKey>__<tool>;仅字母/数字/连字符,避用下划线;应用内唯一,且不得与宿主注册表/用户级 serverKey 冲突——防遮蔽)';
COMMENT ON COLUMN ia_mcp_server_config.name IS '展示名';
COMMENT ON COLUMN ia_mcp_server_config.endpoint_url IS '三方 MCP Streamable HTTP 端点 URL';
COMMENT ON COLUMN ia_mcp_server_config.transport IS '传输方式:streamable-http(P4-W13 仅此一种)';
COMMENT ON COLUMN ia_mcp_server_config.auth_type IS
    '鉴权策略:STATIC_HEADER(静态头)/OAUTH(CIMD/DCR + RFC 8707;P4-W13 仅枚举位,配置即 501)';
COMMENT ON COLUMN ia_mcp_server_config.header_name IS '静态头名(auth_type=STATIC_HEADER 时必填)';
COMMENT ON COLUMN ia_mcp_server_config.credentials IS
    '静态头值/凭据(TEXT;加密存储可延后;值不进审计/日志)';
COMMENT ON COLUMN ia_mcp_server_config.timeout_seconds IS 'tools/call 超时(秒)';
COMMENT ON COLUMN ia_mcp_server_config.enabled IS '启停(停用即从目录摘除并失效缓存)';
COMMENT ON COLUMN ia_mcp_server_config.deleted IS '逻辑删除标志';
COMMENT ON COLUMN ia_mcp_server_config.create_time IS '创建时间';
COMMENT ON COLUMN ia_mcp_server_config.update_time IS '更新时间';

-- ---------------------------------------------------------------------
-- 2. ia_mcp_user_server:用户级三方 MCP 服务器(用户自接;行级 userId 隔离)
-- ---------------------------------------------------------------------
CREATE TABLE ia_mcp_user_server (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id          BIGINT       NOT NULL DEFAULT 1,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    user_id         BIGINT       NOT NULL,
    server_key      VARCHAR(64)  NOT NULL,
    name            VARCHAR(128) NOT NULL,
    endpoint_url    VARCHAR(2048) NOT NULL,
    transport       VARCHAR(32)  NOT NULL DEFAULT 'streamable-http',
    auth_type       VARCHAR(32)  NOT NULL DEFAULT 'STATIC_HEADER',
    header_name     VARCHAR(128),
    credentials     TEXT,
    timeout_seconds INT          NOT NULL DEFAULT 30,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ia_mcp_user_server_key UNIQUE (app_id, user_id, server_key)
);

CREATE INDEX idx_ia_mcp_user_server_user
    ON ia_mcp_user_server (app_id, user_id);

COMMENT ON TABLE ia_mcp_user_server IS
    '用户级三方 MCP 服务器配置(用户在会话/设置域自接;行级 userId 隔离,他人不可见)';
COMMENT ON COLUMN ia_mcp_user_server.app_id IS '所属应用;单应用部署固定为 1';
COMMENT ON COLUMN ia_mcp_user_server.tenant_id IS '所属租户(团队)ID(用户面请求经行级拦截器落值)';
COMMENT ON COLUMN ia_mcp_user_server.user_id IS '所属用户(行级隔离:仅本人目录可见/可调用)';
COMMENT ON COLUMN ia_mcp_user_server.server_key IS
    '服务器键(FQN 命名空间;规则同 ia_mcp_server_config,且不得与应用级/宿主 serverKey 冲突)';
COMMENT ON COLUMN ia_mcp_user_server.name IS '展示名';
COMMENT ON COLUMN ia_mcp_user_server.endpoint_url IS '三方 MCP Streamable HTTP 端点 URL';
COMMENT ON COLUMN ia_mcp_user_server.transport IS '传输方式:streamable-http(P4-W13 仅此一种)';
COMMENT ON COLUMN ia_mcp_user_server.auth_type IS
    '鉴权策略:STATIC_HEADER/OAUTH(P4-W13 仅枚举位,OAUTH 配置即 501)';
COMMENT ON COLUMN ia_mcp_user_server.header_name IS '静态头名(auth_type=STATIC_HEADER 时必填)';
COMMENT ON COLUMN ia_mcp_user_server.credentials IS
    '静态头值/凭据(TEXT;加密存储可延后;值不进审计/日志)';
COMMENT ON COLUMN ia_mcp_user_server.timeout_seconds IS 'tools/call 超时(秒)';
COMMENT ON COLUMN ia_mcp_user_server.enabled IS '启停(停用即从本人目录摘除并失效缓存)';
COMMENT ON COLUMN ia_mcp_user_server.deleted IS '逻辑删除标志';
COMMENT ON COLUMN ia_mcp_user_server.create_time IS '创建时间';
COMMENT ON COLUMN ia_mcp_user_server.update_time IS '更新时间';
