-- =====================================================================
-- InnerAgent V19 (P4-W13「Skill 体系」,合并时自 V17 顺延:V18 已被并行
-- 批次(三方 MCP)占用):应用级 Skill 目录 —— ia_skill / ia_skill_file。
--
-- PRD §6.4 M4:内置 Skill 库 + 用户/应用 Skill 导入与激活;zip 上传先
-- 预览校验再导入;激活上限默认 8;用户自定义 Skill 仅本人可见(用户级
-- 走 workspace 存储,见 AgentUserSkillService,不落本表——本表只收
-- 「应用级」管理面 Skill:admin 导入、激活门控、停用/删除、审计留痕)。
--
-- 表:
--   ia_skill       Skill 主行:名称/描述/版本/状态(active|inactive)/
--                  来源(import|builtin)/内容指纹/清单 JSON(TEXT)。
--   ia_skill_file  Skill 文件内容(SKILL.md 与资源;文本 utf-8 直存、
--                  二进制 base64;同 V15/R3 DEF-08 教训:一律 TEXT,
--                  不用 JSONB/bytea,序列化收敛在服务层)。
--
-- 教训落档(R3 DEF-08 / V15 取舍):manifest_json 列 TEXT 存 JSON 字符串,
-- 不用 JSONB(共享实体整行 UPDATE 携带 JSONB 列在真实 PG 连接上绑定失败)。
-- 内容指纹 content_sha256 由服务层计算,预览→确认两段上传的完整性与
-- 运行快照对照均以它为准。
-- =====================================================================

CREATE TABLE ia_skill (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id         BIGINT        NOT NULL DEFAULT 1,
    name           VARCHAR(64)   NOT NULL,
    display_name   VARCHAR(64),
    description    VARCHAR(1024) NOT NULL,
    version        VARCHAR(32),
    status         VARCHAR(16)   NOT NULL DEFAULT 'inactive',
    source         VARCHAR(16)   NOT NULL DEFAULT 'import',
    content_sha256 CHAR(64)      NOT NULL,
    manifest_json  TEXT          NOT NULL,
    activated_at   TIMESTAMP,
    activated_by   BIGINT,
    deleted        BOOLEAN       NOT NULL DEFAULT FALSE,
    create_time    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ia_skill_app_name UNIQUE (app_id, name),
    CONSTRAINT chk_ia_skill_status CHECK (status IN ('inactive', 'active')),
    CONSTRAINT chk_ia_skill_source CHECK (source IN ('import', 'builtin'))
);

COMMENT ON TABLE ia_skill IS '应用级 Skill 目录表(P4-W13 M4;admin 导入/激活门控;用户级 Skill 走 workspace 不落本表)';
COMMENT ON COLUMN ia_skill.id IS '主键ID';
COMMENT ON COLUMN ia_skill.app_id IS '所属应用;单应用部署固定为 1(行级拦截器注入)';
COMMENT ON COLUMN ia_skill.name IS 'Skill 业务名(= skill.json.name,kebab-case,应用内唯一)';
COMMENT ON COLUMN ia_skill.display_name IS '显示名称(缺省=name)';
COMMENT ON COLUMN ia_skill.description IS '描述(= skill.json.description)';
COMMENT ON COLUMN ia_skill.version IS 'Skill 版本(= skill.json.version,可空)';
COMMENT ON COLUMN ia_skill.status IS '激活状态:inactive-未激活(不进上下文)/active-已激活(应用内同时上限 8)';
COMMENT ON COLUMN ia_skill.source IS '来源:import-管理面 zip 导入/builtin-平台内置(内置行仅登记占位,内容以 classpath 仓库为准)';
COMMENT ON COLUMN ia_skill.content_sha256 IS '内容指纹(SKILL.md+全部文件的规范哈希;预览/确认/快照对照)';
COMMENT ON COLUMN ia_skill.manifest_json IS 'skill.json 清单原文(TEXT 存 JSON 字符串,不用 JSONB——R3 DEF-08 教训)';
COMMENT ON COLUMN ia_skill.activated_at IS '最近一次激活时间(停用后置 NULL)';
COMMENT ON COLUMN ia_skill.activated_by IS '最近一次激活操作者(admin 账号/操作人 ID)';
COMMENT ON COLUMN ia_skill.deleted IS '逻辑删除标志(删除后同名再导入按复活处理,满足唯一键)';
COMMENT ON COLUMN ia_skill.create_time IS '创建时间';
COMMENT ON COLUMN ia_skill.update_time IS '更新时间';

CREATE INDEX idx_ia_skill_app_status
    ON ia_skill (app_id, status)
    WHERE deleted = FALSE;

-- ---------------------------------------------------------------------

CREATE TABLE ia_skill_file (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id      BIGINT        NOT NULL DEFAULT 1,
    skill_id    BIGINT        NOT NULL,
    path        VARCHAR(512)  NOT NULL,
    encoding    VARCHAR(16)   NOT NULL DEFAULT 'utf-8',
    content     TEXT          NOT NULL,
    size_bytes  BIGINT        NOT NULL,
    create_time TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ia_skill_file UNIQUE (skill_id, path),
    CONSTRAINT chk_ia_skill_file_encoding CHECK (encoding IN ('utf-8', 'base64'))
);

COMMENT ON TABLE ia_skill_file IS 'Skill 文件内容表(SKILL.md 与资源;整包替换,随 ia_skill 生命周期)';
COMMENT ON COLUMN ia_skill_file.id IS '主键ID';
COMMENT ON COLUMN ia_skill_file.app_id IS '所属应用(与主行一致,便于应用级检索)';
COMMENT ON COLUMN ia_skill_file.skill_id IS '所属 Skill(ia_skill.id)';
COMMENT ON COLUMN ia_skill_file.path IS 'Skill 包内相对路径(导入时已拒穿越/绝对路径/symlink)';
COMMENT ON COLUMN ia_skill_file.encoding IS '内容编码:utf-8-原文文本/base64-二进制(AgentUserSkillService.fileValue 同形)';
COMMENT ON COLUMN ia_skill_file.content IS '文件内容(utf-8 原文或 base64 字符串;TEXT 列)';
COMMENT ON COLUMN ia_skill_file.size_bytes IS '原始字节数(解码后;用于上限校验回放)';
COMMENT ON COLUMN ia_skill_file.create_time IS '创建时间';
