-- =====================================================================
-- InnerAgent V1:Agent 核心表(Agent 定义/对话/消息/运行/事件/模型调用量)
-- 移植自融光 ai-fusion-video 迁移(参考源,列定义逐一对照):
--   * B1.1.0.0.8__baseline_1.0.0.sql(afv_agent_conversation / afv_agent_message)
--   * V1.0.4.0.1__expand_script_and_agent_message_text_columns.sql(message.content 扩容)
--   * V1.0.6.1.5__agent_run_and_event.sql(afv_agent_run / afv_agent_event / afv_agent_model_call_usage)
--   * V1.1.0.0.8__agent_state_retention.sql(conversation 状态保留列与索引)
-- 改造规则(见 02-技术方案 §5.1):
--   * MySQL 8 -> PostgreSQL 17 方言;afv_ 前缀 -> ia_ 前缀。
--   * 所有业务表增加 app_id BIGINT NOT NULL DEFAULT 1(所属应用;单应用部署固定为 1,
--     P1 接入 AppContext 后显式写入)。
--   * 公共列对齐实体基类:实体继承 TenantBaseEntity 的表保留 tenant_id;deleted 用 BOOLEAN。
--   * ia_agent_event.schema_version:事件载荷结构版本(持久事件版本化,fail-fast 兼容策略)。
--   * MySQL AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY;DATETIME -> TIMESTAMP;
--     MEDIUMTEXT/LONGTEXT -> TEXT(TOAST 无 16MB 上限)。
--   * PostgreSQL 无 ON UPDATE CURRENT_TIMESTAMP:update_time 由应用层
--     (MyBatis-Plus FieldFill.INSERT_UPDATE / 运行时 SQL 显式赋值)维护。
--   * 索引按融光原样保留(改名换前缀);补充应用维度查询索引
--     idx_ia_conv_app_user_time(融光注释中的 updated_at 对应本表 update_time);
--     ia_agent_event(run_id, sequence_no) 查询已由唯一约束 uk_ia_agent_event_sequence
--     前缀覆盖,不重复建索引。
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. ia_agent_definition:Agent 定义表(新增,替代代码内 AiAgentRegistry)
-- ---------------------------------------------------------------------
CREATE TABLE ia_agent_definition (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id                 BIGINT       NOT NULL DEFAULT 1,
    agent_key              VARCHAR(64)  NOT NULL,
    kind                   VARCHAR(8)   NOT NULL,
    title                  VARCHAR(255) NOT NULL,
    system_prompt          TEXT,
    instruction_template   TEXT,
    model_id               BIGINT,
    tool_whitelist_json    TEXT,
    sub_agent_tools_json   TEXT,
    context_template_json  TEXT,
    greeting               TEXT,
    enabled                BOOLEAN      NOT NULL DEFAULT TRUE,
    deleted                BOOLEAN      NOT NULL DEFAULT FALSE,
    create_time            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ia_agent_definition_key UNIQUE (app_id, agent_key),
    CONSTRAINT chk_ia_agent_definition_kind CHECK (kind IN ('main', 'sub'))
);

COMMENT ON TABLE ia_agent_definition IS 'Agent 定义表(数据化替代代码内 Agent 注册表)';
COMMENT ON COLUMN ia_agent_definition.id IS '主键ID';
COMMENT ON COLUMN ia_agent_definition.app_id IS '所属应用;单应用部署固定为 1,P1 接入 AppContext 后显式写入';
COMMENT ON COLUMN ia_agent_definition.agent_key IS 'Agent 业务标识(应用内唯一)';
COMMENT ON COLUMN ia_agent_definition.kind IS 'Agent 种类:main-主 Agent sub-子 Agent';
COMMENT ON COLUMN ia_agent_definition.title IS 'Agent 显示名称';
COMMENT ON COLUMN ia_agent_definition.system_prompt IS '系统提示词';
COMMENT ON COLUMN ia_agent_definition.instruction_template IS '指令模板';
COMMENT ON COLUMN ia_agent_definition.model_id IS '默认关联模型ID(ia_ai_model.id)';
COMMENT ON COLUMN ia_agent_definition.tool_whitelist_json IS '工具白名单 JSON(工具 FQN 列表)';
COMMENT ON COLUMN ia_agent_definition.sub_agent_tools_json IS '子 Agent 可用工具 JSON';
COMMENT ON COLUMN ia_agent_definition.context_template_json IS '上下文注入模板 JSON';
COMMENT ON COLUMN ia_agent_definition.greeting IS '开场白';
COMMENT ON COLUMN ia_agent_definition.enabled IS '是否启用:TRUE-启用 FALSE-停用';
COMMENT ON COLUMN ia_agent_definition.deleted IS '逻辑删除标志';
COMMENT ON COLUMN ia_agent_definition.create_time IS '创建时间';
COMMENT ON COLUMN ia_agent_definition.update_time IS '更新时间';

-- ---------------------------------------------------------------------
-- 2. ia_agent_conversation:Agent 对话索引表(源:afv_agent_conversation)
-- ---------------------------------------------------------------------
CREATE TABLE ia_agent_conversation (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id                     BIGINT      NOT NULL DEFAULT 1,
    tenant_id                  BIGINT      NOT NULL DEFAULT 0,
    conversation_id            VARCHAR(64) NOT NULL,
    user_id                    BIGINT,
    project_id                 BIGINT,
    context_type               VARCHAR(50),
    agent_type                 VARCHAR(64),
    category                   VARCHAR(32),
    context_id                 BIGINT,
    title                      VARCHAR(255) DEFAULT '新对话',
    message_count              INT         DEFAULT 0,
    last_message_time          TIMESTAMP,
    status                     VARCHAR(32),
    deleted                    BOOLEAN     NOT NULL DEFAULT FALSE,
    create_time                TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time                TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    next_message_order         BIGINT      NOT NULL DEFAULT 1,
    agent_state_last_active_at TIMESTAMP(3),
    agent_state_expired_at     TIMESTAMP(3),
    CONSTRAINT uk_ia_agent_conversation_cid UNIQUE (conversation_id)
);

CREATE INDEX idx_ia_conv_project_context
    ON ia_agent_conversation (project_id, context_type, context_id);
CREATE INDEX idx_ia_conv_user
    ON ia_agent_conversation (user_id);
CREATE INDEX idx_ia_agent_conversation_state_retention
    ON ia_agent_conversation (agent_state_expired_at, agent_state_last_active_at, id);
CREATE INDEX idx_ia_conv_app_user_time
    ON ia_agent_conversation (app_id, user_id, update_time);

COMMENT ON TABLE ia_agent_conversation IS 'Agent对话索引表';
COMMENT ON COLUMN ia_agent_conversation.id IS '主键ID';
COMMENT ON COLUMN ia_agent_conversation.app_id IS '所属应用;单应用部署固定为 1,P1 接入 AppContext 后显式写入';
COMMENT ON COLUMN ia_agent_conversation.tenant_id IS '所属租户(团队)ID';
COMMENT ON COLUMN ia_agent_conversation.conversation_id IS '对话唯一标识(UUID)';
COMMENT ON COLUMN ia_agent_conversation.user_id IS '所属用户ID';
COMMENT ON COLUMN ia_agent_conversation.project_id IS '关联项目ID';
COMMENT ON COLUMN ia_agent_conversation.context_type IS '上下文类型(project/script/storyboard 等)';
COMMENT ON COLUMN ia_agent_conversation.agent_type IS 'Agent类型(对应 ia_agent_definition.agent_key)';
COMMENT ON COLUMN ia_agent_conversation.category IS '对话分类标签';
COMMENT ON COLUMN ia_agent_conversation.context_id IS '上下文对象ID';
COMMENT ON COLUMN ia_agent_conversation.title IS '对话标题';
COMMENT ON COLUMN ia_agent_conversation.message_count IS '消息总数(未删除可见消息数)';
COMMENT ON COLUMN ia_agent_conversation.last_message_time IS '最后消息时间';
COMMENT ON COLUMN ia_agent_conversation.status IS '对话状态:active-进行中 closed-已关闭';
COMMENT ON COLUMN ia_agent_conversation.deleted IS '逻辑删除标志';
COMMENT ON COLUMN ia_agent_conversation.create_time IS '创建时间';
COMMENT ON COLUMN ia_agent_conversation.update_time IS '更新时间';
COMMENT ON COLUMN ia_agent_conversation.next_message_order IS '下一条消息的全历史唯一顺序号';
COMMENT ON COLUMN ia_agent_conversation.agent_state_last_active_at IS 'AgentState 最近一次进入可继续使用状态的时间';
COMMENT ON COLUMN ia_agent_conversation.agent_state_expired_at IS 'AgentState 已完成物理清理的时间';

-- ---------------------------------------------------------------------
-- 3. ia_agent_message:Agent 消息表(源:afv_agent_message,
--    含 V1.0.4.0.1 content 扩容与 V1.0.6.1.5 run_id/projection_key 改造)
-- ---------------------------------------------------------------------
CREATE TABLE ia_agent_message (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id               BIGINT      NOT NULL DEFAULT 1,
    tenant_id            BIGINT      NOT NULL DEFAULT 0,
    conversation_id      VARCHAR(64) NOT NULL,
    role                 VARCHAR(20) NOT NULL,
    content              TEXT,
    references_json      TEXT,
    tool_name            VARCHAR(100),
    tool_status          VARCHAR(20),
    tool_call_id         VARCHAR(128),
    parent_tool_call_id  VARCHAR(128),
    reasoning_content    TEXT,
    reasoning_duration_ms BIGINT,
    message_order        BIGINT      NOT NULL,
    deleted              BOOLEAN     NOT NULL DEFAULT FALSE,
    create_time          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    run_id               VARCHAR(64),
    projection_key       VARCHAR(64),
    CONSTRAINT uk_ia_agent_message_conv_order UNIQUE (conversation_id, message_order),
    CONSTRAINT uk_ia_agent_message_projection_key UNIQUE (projection_key)
);

CREATE INDEX idx_ia_msg_conversation
    ON ia_agent_message (conversation_id);
CREATE INDEX idx_ia_agent_message_conv_run_order
    ON ia_agent_message (conversation_id, run_id, message_order);

COMMENT ON TABLE ia_agent_message IS 'Agent消息表';
COMMENT ON COLUMN ia_agent_message.id IS '主键ID';
COMMENT ON COLUMN ia_agent_message.app_id IS '所属应用;单应用部署固定为 1,P1 接入 AppContext 后显式写入';
COMMENT ON COLUMN ia_agent_message.tenant_id IS '所属租户(团队)ID';
COMMENT ON COLUMN ia_agent_message.conversation_id IS '所属对话ID(UUID,关联 ia_agent_conversation.conversation_id)';
COMMENT ON COLUMN ia_agent_message.role IS '消息角色:user/assistant/system/tool';
COMMENT ON COLUMN ia_agent_message.content IS '消息文本内容';
COMMENT ON COLUMN ia_agent_message.references_json IS '引用资源JSON';
COMMENT ON COLUMN ia_agent_message.tool_name IS '工具调用名称(role=tool 时)';
COMMENT ON COLUMN ia_agent_message.tool_status IS '工具执行状态:running/success/error/cancelled';
COMMENT ON COLUMN ia_agent_message.tool_call_id IS '工具调用ID(关联同一次调用的发起和结果)';
COMMENT ON COLUMN ia_agent_message.parent_tool_call_id IS '父级工具调用ID(子Agent事件归属到父工具调用)';
COMMENT ON COLUMN ia_agent_message.reasoning_content IS 'AI推理过程内容(思维链)';
COMMENT ON COLUMN ia_agent_message.reasoning_duration_ms IS 'AI推理耗时(毫秒)';
COMMENT ON COLUMN ia_agent_message.message_order IS '会话内全历史唯一顺序号(从 1 递增)';
COMMENT ON COLUMN ia_agent_message.deleted IS '逻辑删除标志';
COMMENT ON COLUMN ia_agent_message.create_time IS '创建时间';
COMMENT ON COLUMN ia_agent_message.update_time IS '更新时间';
COMMENT ON COLUMN ia_agent_message.run_id IS '产生该消息的运行ID(ia_agent_run.run_id)';
COMMENT ON COLUMN ia_agent_message.projection_key IS '事件投影幂等键(空表示手工消息)';

-- ---------------------------------------------------------------------
-- 4. ia_agent_run:Agent 运行表(源:afv_agent_run,AgentScope V2 持久运行)
-- ---------------------------------------------------------------------
CREATE TABLE ia_agent_run (
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id                         BIGINT      NOT NULL DEFAULT 1,
    tenant_id                      BIGINT      NOT NULL DEFAULT 0,
    run_id                         VARCHAR(64) NOT NULL,
    conversation_id                VARCHAR(64) NOT NULL,
    user_id                        BIGINT      NOT NULL,
    project_id                     BIGINT,
    agent_type                     VARCHAR(64),
    parent_run_id                  VARCHAR(64),
    parent_tool_call_id            VARCHAR(128),
    agent_name                     VARCHAR(128),
    kernel_fingerprint             VARCHAR(64) NOT NULL,
    agent_definition_snapshot_json TEXT        NOT NULL,
    agent_state_session_id         VARCHAR(255) NOT NULL,
    status                         VARCHAR(32) NOT NULL,
    owner_instance_id              VARCHAR(128),
    owner_epoch                    BIGINT      NOT NULL DEFAULT 0,
    lease_until                    TIMESTAMP(3),
    next_sequence                  BIGINT      NOT NULL DEFAULT 1,
    terminal_sequence              BIGINT,
    terminal_output_type           VARCHAR(32),
    cancel_requested_at            TIMESTAMP(3),
    cancel_broadcast_at            TIMESTAMP(3),
    cancel_acknowledged_at         TIMESTAMP(3),
    cancel_next_attempt_at         TIMESTAMP(3),
    waiting_reply_id               VARCHAR(128),
    waiting_tool_call_id           VARCHAR(128),
    waiting_tool_name              VARCHAR(128),
    wait_expires_at                TIMESTAMP(3),
    paused_through_sequence        BIGINT,
    deadline_at                    TIMESTAMP(3) NOT NULL,
    started_at                     TIMESTAMP(3) NOT NULL,
    heartbeat_at                   TIMESTAMP(3),
    finished_at                    TIMESTAMP(3),
    error_code                     VARCHAR(64),
    error_message                  TEXT,
    usage_settled                  BOOLEAN     NOT NULL DEFAULT FALSE,
    usage_settled_at               TIMESTAMP(3),
    projected_through_sequence     BIGINT      NOT NULL DEFAULT 0,
    projection_completed_at        TIMESTAMP(3),
    active_conversation_id         VARCHAR(64) GENERATED ALWAYS AS (
        CASE
            WHEN parent_run_id IS NULL
                 AND status IN (
                     'RUNNING',
                     'WAITING_CONFIRMATION',
                     'WAITING_EXTERNAL',
                     'CANCEL_REQUESTED')
            THEN conversation_id
        END
    ) STORED,
    create_time                    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time                    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ia_agent_run_id UNIQUE (run_id),
    CONSTRAINT uk_ia_agent_run_active UNIQUE (active_conversation_id),
    CONSTRAINT uk_ia_agent_run_parent_tool UNIQUE (parent_run_id, parent_tool_call_id),
    CONSTRAINT chk_ia_agent_run_parent_identity CHECK (
        (parent_run_id IS NULL AND parent_tool_call_id IS NULL)
        OR (parent_run_id IS NOT NULL
            AND parent_tool_call_id IS NOT NULL
            AND agent_name IS NOT NULL)),
    CONSTRAINT chk_ia_agent_run_status CHECK (
        status IN (
            'RUNNING',
            'WAITING_CONFIRMATION',
            'WAITING_EXTERNAL',
            'CANCEL_REQUESTED',
            'COMPLETED',
            'FAILED',
            'CANCELLED')),
    CONSTRAINT chk_ia_agent_run_usage_settled CHECK (usage_settled IN (FALSE, TRUE))
);

CREATE INDEX idx_ia_agent_run_conversation_status
    ON ia_agent_run (conversation_id, status, id);
CREATE INDEX idx_ia_agent_run_parent_status
    ON ia_agent_run (parent_run_id, status, id);
CREATE INDEX idx_ia_agent_run_user_status
    ON ia_agent_run (user_id, status, update_time);
CREATE INDEX idx_ia_agent_run_lease
    ON ia_agent_run (status, lease_until);
CREATE INDEX idx_ia_agent_run_status_deadline
    ON ia_agent_run (status, deadline_at, id);
CREATE INDEX idx_ia_agent_run_cancel
    ON ia_agent_run (status, cancel_next_attempt_at);

COMMENT ON TABLE ia_agent_run IS 'Agent运行表(AgentScope V2 持久运行)';
COMMENT ON COLUMN ia_agent_run.id IS '主键ID';
COMMENT ON COLUMN ia_agent_run.app_id IS '所属应用;单应用部署固定为 1,P1 接入 AppContext 后显式写入';
COMMENT ON COLUMN ia_agent_run.tenant_id IS '所属租户(团队)ID';
COMMENT ON COLUMN ia_agent_run.run_id IS '运行唯一标识';
COMMENT ON COLUMN ia_agent_run.conversation_id IS '所属对话ID(UUID)';
COMMENT ON COLUMN ia_agent_run.user_id IS '发起用户ID';
COMMENT ON COLUMN ia_agent_run.project_id IS '关联项目ID';
COMMENT ON COLUMN ia_agent_run.agent_type IS 'Agent类型(对应 ia_agent_definition.agent_key)';
COMMENT ON COLUMN ia_agent_run.parent_run_id IS '父运行ID(子 Agent 运行时非空)';
COMMENT ON COLUMN ia_agent_run.parent_tool_call_id IS '父级工具调用ID(子 Agent 运行时非空)';
COMMENT ON COLUMN ia_agent_run.agent_name IS '子 Agent 名称(子 Agent 运行时非空)';
COMMENT ON COLUMN ia_agent_run.kernel_fingerprint IS '内核指纹(启动内核版本标识)';
COMMENT ON COLUMN ia_agent_run.agent_definition_snapshot_json IS 'Agent 定义快照 JSON(运行期内冻结)';
COMMENT ON COLUMN ia_agent_run.agent_state_session_id IS 'AgentState 会话ID';
COMMENT ON COLUMN ia_agent_run.status IS '运行状态:RUNNING/WAITING_CONFIRMATION/WAITING_EXTERNAL/CANCEL_REQUESTED/COMPLETED/FAILED/CANCELLED';
COMMENT ON COLUMN ia_agent_run.owner_instance_id IS '持有租约的实例标识';
COMMENT ON COLUMN ia_agent_run.owner_epoch IS '租约代次(防陈旧持有者)';
COMMENT ON COLUMN ia_agent_run.lease_until IS '租约到期时间';
COMMENT ON COLUMN ia_agent_run.next_sequence IS '下一个事件序号';
COMMENT ON COLUMN ia_agent_run.terminal_sequence IS '终态事件序号(事件流结束时回填)';
COMMENT ON COLUMN ia_agent_run.terminal_output_type IS '终态事件输出类型';
COMMENT ON COLUMN ia_agent_run.cancel_requested_at IS '取消请求时间';
COMMENT ON COLUMN ia_agent_run.cancel_broadcast_at IS '取消广播时间';
COMMENT ON COLUMN ia_agent_run.cancel_acknowledged_at IS '取消确认时间';
COMMENT ON COLUMN ia_agent_run.cancel_next_attempt_at IS '下次取消重试时间';
COMMENT ON COLUMN ia_agent_run.waiting_reply_id IS '等待确认的回复ID';
COMMENT ON COLUMN ia_agent_run.waiting_tool_call_id IS '等待外部结果的工具调用ID';
COMMENT ON COLUMN ia_agent_run.waiting_tool_name IS '等待外部结果的工具名称';
COMMENT ON COLUMN ia_agent_run.wait_expires_at IS '等待超时时间';
COMMENT ON COLUMN ia_agent_run.paused_through_sequence IS '暂停时已消费到的事件序号';
COMMENT ON COLUMN ia_agent_run.deadline_at IS '运行截止时间(超时强杀)';
COMMENT ON COLUMN ia_agent_run.started_at IS '开始时间';
COMMENT ON COLUMN ia_agent_run.heartbeat_at IS '心跳时间';
COMMENT ON COLUMN ia_agent_run.finished_at IS '结束时间';
COMMENT ON COLUMN ia_agent_run.error_code IS '错误码';
COMMENT ON COLUMN ia_agent_run.error_message IS '错误信息';
COMMENT ON COLUMN ia_agent_run.usage_settled IS '用量是否已结算:TRUE-已结算 FALSE-未结算';
COMMENT ON COLUMN ia_agent_run.usage_settled_at IS '用量结算完成时间';
COMMENT ON COLUMN ia_agent_run.projected_through_sequence IS '已投影到消息表的最大事件序号';
COMMENT ON COLUMN ia_agent_run.projection_completed_at IS '投影完成时间';
COMMENT ON COLUMN ia_agent_run.active_conversation_id IS '活动会话ID(生成列:根运行且处于活动状态时等于 conversation_id,否则为空,支撑会话级唯一活动运行)';
COMMENT ON COLUMN ia_agent_run.create_time IS '创建时间';
COMMENT ON COLUMN ia_agent_run.update_time IS '更新时间';

-- ---------------------------------------------------------------------
-- 5. ia_agent_event:Agent 事件日志表(源:afv_agent_event,已提交事件流水)
-- ---------------------------------------------------------------------
CREATE TABLE ia_agent_event (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id                  BIGINT       NOT NULL DEFAULT 1,
    tenant_id               BIGINT       NOT NULL DEFAULT 0,
    run_id                  VARCHAR(64)  NOT NULL,
    sequence_no             BIGINT       NOT NULL,
    schema_version          INT          NOT NULL DEFAULT 1,
    raw_event_id            VARCHAR(128),
    raw_event_type          VARCHAR(64)  NOT NULL,
    source                  VARCHAR(255),
    reply_id                VARCHAR(128),
    block_id                VARCHAR(128),
    tool_call_id            VARCHAR(128),
    parent_tool_call_id     VARCHAR(128),
    agent_name              VARCHAR(128),
    output_type             VARCHAR(32),
    payload_json            TEXT         NOT NULL,
    event_created_at        TIMESTAMP(3),
    redis_published_at      TIMESTAMP(3),
    publish_required        BOOLEAN      NOT NULL,
    publish_status          VARCHAR(16)  NOT NULL,
    publish_claim_owner     VARCHAR(128),
    publish_claim_until     TIMESTAMP(3),
    next_publish_attempt_at TIMESTAMP(3),
    last_publish_error      VARCHAR(1024),
    publish_attempts        INT          NOT NULL DEFAULT 0,
    create_time             TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ia_agent_event_sequence UNIQUE (run_id, sequence_no),
    CONSTRAINT chk_ia_agent_event_publish_state CHECK (
        (publish_required = FALSE AND publish_status = 'NOT_REQUIRED')
        OR (publish_required = TRUE
            AND publish_status IN ('PENDING', 'CLAIMED', 'PUBLISHED'))),
    CONSTRAINT chk_ia_agent_event_publish_attempts CHECK (publish_attempts >= 0),
    CONSTRAINT chk_ia_agent_event_sequence CHECK (sequence_no >= 1),
    CONSTRAINT chk_ia_agent_event_schema_version CHECK (schema_version >= 1)
);

CREATE INDEX idx_ia_agent_event_projection
    ON ia_agent_event (run_id, output_type, sequence_no);
CREATE INDEX idx_ia_agent_event_publish
    ON ia_agent_event (publish_status, next_publish_attempt_at, id);
CREATE INDEX idx_ia_agent_event_raw
    ON ia_agent_event (run_id, raw_event_id);
-- 说明:ia_agent_event(run_id, sequence_no) 查询索引由
-- uk_ia_agent_event_sequence 前缀覆盖,按融光原样不再重复创建。

COMMENT ON TABLE ia_agent_event IS 'Agent事件日志表(AgentScope V2 已提交事件流水,仅追加)';
COMMENT ON COLUMN ia_agent_event.id IS '主键ID';
COMMENT ON COLUMN ia_agent_event.app_id IS '所属应用;单应用部署固定为 1,P1 接入 AppContext 后显式写入';
COMMENT ON COLUMN ia_agent_event.tenant_id IS '所属租户(团队)ID';
COMMENT ON COLUMN ia_agent_event.run_id IS '所属运行ID';
COMMENT ON COLUMN ia_agent_event.sequence_no IS '运行内事件序号(从 1 递增)';
COMMENT ON COLUMN ia_agent_event.schema_version IS '事件载荷结构版本(payload 结构版本化,消费端 fail-fast 兼容)';
COMMENT ON COLUMN ia_agent_event.raw_event_id IS '内核原始事件ID';
COMMENT ON COLUMN ia_agent_event.raw_event_type IS '内核原始事件类型';
COMMENT ON COLUMN ia_agent_event.source IS '事件来源标识';
COMMENT ON COLUMN ia_agent_event.reply_id IS '关联回复消息ID';
COMMENT ON COLUMN ia_agent_event.block_id IS '关联内容块ID';
COMMENT ON COLUMN ia_agent_event.tool_call_id IS '关联工具调用ID';
COMMENT ON COLUMN ia_agent_event.parent_tool_call_id IS '关联父级工具调用ID';
COMMENT ON COLUMN ia_agent_event.agent_name IS '产生事件的 Agent 名称';
COMMENT ON COLUMN ia_agent_event.output_type IS '输出类型(投影过滤用)';
COMMENT ON COLUMN ia_agent_event.payload_json IS '事件载荷 JSON';
COMMENT ON COLUMN ia_agent_event.event_created_at IS '内核事件产生时间';
COMMENT ON COLUMN ia_agent_event.redis_published_at IS 'Redis 发布完成时间';
COMMENT ON COLUMN ia_agent_event.publish_required IS '是否需要发布到 Redis 通道';
COMMENT ON COLUMN ia_agent_event.publish_status IS '发布状态:NOT_REQUIRED/PENDING/CLAIMED/PUBLISHED';
COMMENT ON COLUMN ia_agent_event.publish_claim_owner IS '发布任务认领者';
COMMENT ON COLUMN ia_agent_event.publish_claim_until IS '发布任务认领租约到期时间';
COMMENT ON COLUMN ia_agent_event.next_publish_attempt_at IS '下次发布尝试时间';
COMMENT ON COLUMN ia_agent_event.last_publish_error IS '最近一次发布错误';
COMMENT ON COLUMN ia_agent_event.publish_attempts IS '发布尝试次数';
COMMENT ON COLUMN ia_agent_event.create_time IS '创建时间';

-- ---------------------------------------------------------------------
-- 6. ia_agent_model_call_usage:模型调用量表(源:afv_agent_model_call_usage)
-- ---------------------------------------------------------------------
CREATE TABLE ia_agent_model_call_usage (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id                   BIGINT       NOT NULL DEFAULT 1,
    tenant_id                BIGINT       NOT NULL DEFAULT 0,
    run_id                   VARCHAR(64)  NOT NULL,
    model_call_id            VARCHAR(64)  NOT NULL,
    provider                 VARCHAR(64)  NOT NULL,
    model_code               VARCHAR(128) NOT NULL,
    status                   VARCHAR(24)  NOT NULL,
    input_tokens             BIGINT,
    output_tokens            BIGINT,
    reasoning_tokens         BIGINT,
    cache_tokens             BIGINT,
    usage_json               TEXT,
    settlement_status        VARCHAR(24)  NOT NULL,
    settlement_attempts      INT          NOT NULL DEFAULT 0,
    next_settlement_attempt_at TIMESTAMP(3),
    settlement_claim_owner   VARCHAR(128),
    settlement_claim_until   TIMESTAMP(3),
    downstream_settlement_id VARCHAR(128),
    last_settlement_error    VARCHAR(1024),
    started_at               TIMESTAMP(3) NOT NULL,
    finished_at              TIMESTAMP(3),
    create_time              TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time              TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ia_agent_usage_call UNIQUE (run_id, model_call_id),
    CONSTRAINT chk_ia_agent_usage_status CHECK (
        status IN ('STARTED', 'COMPLETED', 'FAILED', 'CANCELLED')),
    CONSTRAINT chk_ia_agent_usage_settlement CHECK (
        settlement_status IN ('PENDING', 'CLAIMED', 'SETTLED')),
    CONSTRAINT chk_ia_agent_usage_settlement_attempts CHECK (settlement_attempts >= 0),
    CONSTRAINT chk_ia_agent_usage_tokens CHECK (
        (input_tokens IS NULL OR input_tokens >= 0)
        AND (output_tokens IS NULL OR output_tokens >= 0)
        AND (reasoning_tokens IS NULL OR reasoning_tokens >= 0)
        AND (cache_tokens IS NULL OR cache_tokens >= 0))
);

CREATE INDEX idx_ia_agent_usage_settlement
    ON ia_agent_model_call_usage (settlement_status, next_settlement_attempt_at, id);
CREATE INDEX idx_ia_agent_usage_run_status
    ON ia_agent_model_call_usage (run_id, status, id);

COMMENT ON TABLE ia_agent_model_call_usage IS 'Agent模型调用用量表(AgentScope V2 model-call 台账,结算 P2 启用)';
COMMENT ON COLUMN ia_agent_model_call_usage.id IS '主键ID';
COMMENT ON COLUMN ia_agent_model_call_usage.app_id IS '所属应用;单应用部署固定为 1,P1 接入 AppContext 后显式写入';
COMMENT ON COLUMN ia_agent_model_call_usage.tenant_id IS '所属租户(团队)ID';
COMMENT ON COLUMN ia_agent_model_call_usage.run_id IS '所属运行ID';
COMMENT ON COLUMN ia_agent_model_call_usage.model_call_id IS '内核模型调用ID(运行内唯一)';
COMMENT ON COLUMN ia_agent_model_call_usage.provider IS '模型服务商标识';
COMMENT ON COLUMN ia_agent_model_call_usage.model_code IS '模型代码标识';
COMMENT ON COLUMN ia_agent_model_call_usage.status IS '调用状态:STARTED/COMPLETED/FAILED/CANCELLED';
COMMENT ON COLUMN ia_agent_model_call_usage.input_tokens IS '输入 token 数';
COMMENT ON COLUMN ia_agent_model_call_usage.output_tokens IS '输出 token 数';
COMMENT ON COLUMN ia_agent_model_call_usage.reasoning_tokens IS '推理(思考)token 数';
COMMENT ON COLUMN ia_agent_model_call_usage.cache_tokens IS '缓存命中 token 数';
COMMENT ON COLUMN ia_agent_model_call_usage.usage_json IS '原始用量 JSON(备用)';
COMMENT ON COLUMN ia_agent_model_call_usage.settlement_status IS '结算状态:PENDING/CLAIMED/SETTLED';
COMMENT ON COLUMN ia_agent_model_call_usage.settlement_attempts IS '结算尝试次数';
COMMENT ON COLUMN ia_agent_model_call_usage.next_settlement_attempt_at IS '下次结算尝试时间';
COMMENT ON COLUMN ia_agent_model_call_usage.settlement_claim_owner IS '结算任务认领者';
COMMENT ON COLUMN ia_agent_model_call_usage.settlement_claim_until IS '结算任务认领租约到期时间';
COMMENT ON COLUMN ia_agent_model_call_usage.downstream_settlement_id IS '下游结算单ID';
COMMENT ON COLUMN ia_agent_model_call_usage.last_settlement_error IS '最近一次结算错误';
COMMENT ON COLUMN ia_agent_model_call_usage.started_at IS '调用开始时间';
COMMENT ON COLUMN ia_agent_model_call_usage.finished_at IS '调用结束时间';
COMMENT ON COLUMN ia_agent_model_call_usage.create_time IS '创建时间';
COMMENT ON COLUMN ia_agent_model_call_usage.update_time IS '更新时间';
