-- =====================================================================
-- InnerAgent V20 (P4-W14「mini 知识库」,合并时自 V19 顺延;ADR-T9/Q4):
-- 无向量轻量知识库 —— ia_kb_document / ia_kb_chunk,检索走 PG tsvector
-- SQL 全文 + 元数据过滤,不引入新中间件(02-技术方案 §4.4)。
--
-- 检索配置(Q4 工程答案):tsv 落列所用 to_tsvector 配置可配
-- (inneragent.kb.search-config,缺省 'simple';zhparser 存在时可配
-- 'zhparser')。服务启动时运行期探测 pg_extension/pg_available_extensions:
-- 请求非 simple 配置而扩展不可得(未预装且无权 CREATE EXTENSION)时
-- 自动降级 'simple' 并 WARN,不阻断启动。中文检索在 simple 配置下用
-- 「按字面/二元切分」近似:CJK 连续段以二元(bigram)空格切分后交给
-- simple 分词(服务层 CjkBigramTextCodec),拉丁词保持原样。
-- 变更 search-config 后须对文档执行重建索引(POST /{id}/rebuild-index),
-- 使存量 tsv 与查询配置一致。
--
-- 表:
--   ia_kb_document 知识库文档主行:app 维度(app_id)/标题/来源/状态
--                  (active|inactive,失效文档不参与检索)/分段数/逻辑删除。
--   ia_kb_chunk    文档分段:doc_id+seq 定位,anchor 记录章节锚点
--                  (PRD「保留来源:文档名/章节/锚点」),tsv 为全文索引列
--                  (GIN);tsv 由服务层 INSERT/UPDATE 时以
--                  to_tsvector(config, 二元切分文本) 服务端计算,
--                  实体不映射该列(MyBatis 不绑定 tsvector)。
--
-- 教训落档:metadata_json 一律 TEXT 存 JSON 字符串,不用 JSONB
-- (R3 DEF-08 / V15 取舍)。检索 SQL(JdbcTemplate,显式携带 app_id)
-- 含 @@/ts_rank 等 PG 全文算子,不走 MyBatis 行级拦截器改写。
--
-- 运行留痕:ia_agent_run 增列 kb_citations_json(TEXT,DEF-08 同款):
-- 组装时命中的知识库分段引用清单(chunkId/documentId/documentTitle/
-- anchor/seq),终态 DONE 事件投影时回填给前端展示来源(可溯源,
-- 事件契约可选字段,不破既有消费者)。
-- =====================================================================

CREATE TABLE ia_kb_document (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id         BIGINT        NOT NULL DEFAULT 1,
    title          VARCHAR(256)  NOT NULL,
    source         VARCHAR(256),
    status         VARCHAR(16)   NOT NULL DEFAULT 'active',
    chunk_count    INT           NOT NULL DEFAULT 0,
    content_sha256 CHAR(64)      NOT NULL,
    metadata_json  TEXT,
    deleted        BOOLEAN       NOT NULL DEFAULT FALSE,
    create_time    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_ia_kb_document_status CHECK (status IN ('active', 'inactive'))
);

COMMENT ON TABLE ia_kb_document IS 'mini 知识库文档主行(P4-W14 M5;无向量,单应用文档数上限缺省 1000,超限提示拆库)';
COMMENT ON COLUMN ia_kb_document.id IS '主键ID';
COMMENT ON COLUMN ia_kb_document.app_id IS '所属应用;单应用部署固定为 1(行级拦截器注入)';
COMMENT ON COLUMN ia_kb_document.title IS '文档名(检索命中来源展示:文档名/章节/锚点)';
COMMENT ON COLUMN ia_kb_document.source IS '来源标识(upload/api/外部系统等,可空;检索元数据过滤位)';
COMMENT ON COLUMN ia_kb_document.status IS '状态:active-参与检索/inactive-失效(标黄,不参与检索)';
COMMENT ON COLUMN ia_kb_document.chunk_count IS '分段数(与 ia_kb_chunk 行数一致,重分段后刷新)';
COMMENT ON COLUMN ia_kb_document.content_sha256 IS '正文指纹(sha256,变更判定与重建对照)';
COMMENT ON COLUMN ia_kb_document.metadata_json IS '结构化元数据(TEXT 存 JSON 字符串,不用 JSONB——R3 DEF-08 教训;可空)';
COMMENT ON COLUMN ia_kb_document.deleted IS '逻辑删除标志(删除文档时其分段行物理清理)';
COMMENT ON COLUMN ia_kb_document.create_time IS '创建时间';
COMMENT ON COLUMN ia_kb_document.update_time IS '更新时间';

CREATE INDEX idx_ia_kb_document_app_status
    ON ia_kb_document (app_id, status)
    WHERE deleted = FALSE;

-- ---------------------------------------------------------------------

CREATE TABLE ia_kb_chunk (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id      BIGINT        NOT NULL DEFAULT 1,
    document_id BIGINT        NOT NULL,
    seq         INT           NOT NULL,
    anchor      VARCHAR(256),
    content     TEXT          NOT NULL,
    char_length INT           NOT NULL,
    tsv         TSVECTOR      NOT NULL,
    create_time TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ia_kb_chunk_doc_seq UNIQUE (document_id, seq)
);

COMMENT ON TABLE ia_kb_chunk IS 'mini 知识库分段表(P4-W14 M5;技术方案 §4.4「分段表」;tsvector 全文索引,无向量)';
COMMENT ON COLUMN ia_kb_chunk.id IS '主键ID';
COMMENT ON COLUMN ia_kb_chunk.app_id IS '所属应用(与文档主行一致,检索免回表过滤)';
COMMENT ON COLUMN ia_kb_chunk.document_id IS '所属文档(ia_kb_document.id)';
COMMENT ON COLUMN ia_kb_chunk.seq IS '分段序号(0 起,文档内连续;引用溯源锚点)';
COMMENT ON COLUMN ia_kb_chunk.anchor IS '章节锚点(分段时的最近标题,可空;来源展示位)';
COMMENT ON COLUMN ia_kb_chunk.content IS '分段正文(原样文本,检索命中后注入「引用资料」区块)';
COMMENT ON COLUMN ia_kb_chunk.char_length IS '正文字符数(注入预算与分段上限校验)';
COMMENT ON COLUMN ia_kb_chunk.tsv IS '全文索引列:to_tsvector(检索配置, CJK 二元切分文本)——服务端计算,GIN 索引;配置变更须重建';
COMMENT ON COLUMN ia_kb_chunk.create_time IS '创建时间';

CREATE INDEX idx_ia_kb_chunk_tsv ON ia_kb_chunk USING GIN (tsv);
CREATE INDEX idx_ia_kb_chunk_doc ON ia_kb_chunk (document_id, seq);

-- ---------------------------------------------------------------------
-- 运行引用留痕(P4-W14 引用溯源):组装命中的分段清单随运行落库,
-- 终态 DONE 事件投影时回填 kbCitations(事件契约可选字段)。
-- ---------------------------------------------------------------------

ALTER TABLE ia_agent_run
    ADD COLUMN kb_citations_json TEXT;

COMMENT ON COLUMN ia_agent_run.kb_citations_json IS
    'mini KB 引用溯源:本次运行注入的知识库分段清单 JSON(TEXT,DEF-08 同款;P4-W14;无命中为 NULL)';
