-- =====================================================================
-- InnerAgent V21 (P4-W15「用户反馈 + 用量统计」,合并时自 V19 顺延:
-- V20 已被并行批次 mini KB 占用)。
--
-- PRD M2(03-开发计划 §7.1 W15):用户反馈(👍/👎);§7.3 验收 6:
-- 反馈事件入库,北极星看板出数(任务完成率代理指标)。
--
-- 表:
--   ia_feedback  用户反馈事件:可空维度(conversation/run/message)+
--                rating(UP/DOWN)+ 可选评语 TEXT。幂等键按产品语义
--                分两级:消息级(conversation+message,👍/👎 按钮主
--                语义)优先,run 级(无消息上下文的整体评价)兜底;
--                同键重复提交 = 覆盖(upsert,不产生重复行),以两级
--                部分唯一索引落地(PG NULLS 不参与唯一,故用 WHERE
--                部分索引而非全表 UNIQUE 约束)。
--
-- 附:ia_agent_model_call_usage 聚合支撑索引(W15 用量统计 admin
-- /usage/summary 按时间窗口 group by;台账既有索引均以 run_id 或
-- settlement 为前导列,时间窗口扫描缺支撑)。
--
-- 教训落档(R3 DEF-08 / V15):comment 一律 TEXT,不用 JSONB/varchar
-- 猜长度;JSON 不落库(本表无 JSON 列,维度列保持标量)。
-- =====================================================================

CREATE TABLE ia_feedback (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id          BIGINT       NOT NULL DEFAULT 1,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    user_id         BIGINT       NOT NULL,
    conversation_id VARCHAR(64),
    run_id          VARCHAR(64),
    message_id      VARCHAR(64),
    rating          VARCHAR(8)   NOT NULL,
    comment         TEXT,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_ia_feedback_rating CHECK (rating IN ('UP', 'DOWN')),
    -- 锚点语义:至少携带 run,或 消息级(conversation+message)完整键
    CONSTRAINT chk_ia_feedback_anchor CHECK (
        run_id IS NOT NULL
        OR (conversation_id IS NOT NULL AND message_id IS NOT NULL))
);

COMMENT ON TABLE ia_feedback IS
    '用户反馈事件表(P4-W15;👍/👎 按钮语义,upsert 覆盖幂等;北极星指标数据源)';
COMMENT ON COLUMN ia_feedback.id IS '主键ID';
COMMENT ON COLUMN ia_feedback.app_id IS '所属应用;单应用部署固定为 1(行级拦截器注入)';
COMMENT ON COLUMN ia_feedback.tenant_id IS '所属租户(团队)ID;用户面请求无租户上下文时落 0';
COMMENT ON COLUMN ia_feedback.user_id IS '反馈用户 ID(embed token 认证链;行级隔离列)';
COMMENT ON COLUMN ia_feedback.conversation_id IS '所属会话 ID(ia_agent_conversation.conversation_id;可空)';
COMMENT ON COLUMN ia_feedback.run_id IS '所属运行 ID(ia_agent_run.run_id;run 级反馈的幂等键,消息级行可作上下文冗余)';
COMMENT ON COLUMN ia_feedback.message_id IS '反馈消息标识(消息投影行 ID;与 conversation_id 组成消息级幂等键)';
COMMENT ON COLUMN ia_feedback.rating IS '反馈取向:UP-👍 / DOWN-👎';
COMMENT ON COLUMN ia_feedback.comment IS '可选文字评语(自由文本,不设 JSON 结构)';
COMMENT ON COLUMN ia_feedback.deleted IS '逻辑删除标志(BaseEntity 统一形态)';
COMMENT ON COLUMN ia_feedback.create_time IS '首次反馈时间';
COMMENT ON COLUMN ia_feedback.update_time IS '最近覆盖时间(重复反馈=覆盖语义)';

-- 消息级幂等键(👍/👎 主语义:同一用户对同一消息重复反馈=覆盖)
CREATE UNIQUE INDEX uk_ia_feedback_message
    ON ia_feedback (app_id, user_id, conversation_id, message_id)
    WHERE conversation_id IS NOT NULL AND message_id IS NOT NULL;

-- run 级幂等键(无消息上下文的整体评价;条件排除消息级行,避免双键歧义)
CREATE UNIQUE INDEX uk_ia_feedback_run
    ON ia_feedback (app_id, user_id, run_id)
    WHERE run_id IS NOT NULL AND conversation_id IS NULL AND message_id IS NULL;

-- 检索/聚合支撑(admin 分页过滤 + 北极星比率)
CREATE INDEX idx_ia_feedback_user_time
    ON ia_feedback (user_id, create_time);
CREATE INDEX idx_ia_feedback_run
    ON ia_feedback (run_id)
    WHERE run_id IS NOT NULL;
CREATE INDEX idx_ia_feedback_conversation
    ON ia_feedback (conversation_id)
    WHERE conversation_id IS NOT NULL;

-- ---------------------------------------------------------------------
-- W15 用量统计聚合支撑(台账时间窗口扫描)
-- ---------------------------------------------------------------------

CREATE INDEX idx_ia_agent_usage_started_at
    ON ia_agent_model_call_usage (started_at);
