-- =====================================================================
-- InnerAgent V2:应用与工具中枢(应用注册/工具注册表/用户授权/审计/模型配置)
-- 表来源:
--   * ia_app / ia_tool_registry / ia_tool_grant / ia_audit_log:新增(02-技术方案 §5.1,
--     列定义按开发计划 P0-T4 任务卡硬性规格)。
--   * ia_model_api_config / ia_ai_model:移植自融光 B1.1.0.0.8__baseline_1.0.0.sql 的
--     afv_api_config / afv_ai_model(文本模型部分)。
-- 改造规则:
--   * MySQL 8 -> PostgreSQL 17;afv_ 前缀 -> ia_ 前缀;所有业务表增加
--     app_id BIGINT NOT NULL DEFAULT 1(所属应用;单应用部署固定为 1)。
--   * ia_model_api_config 去图像/视频专属列:image_protocol、video_protocol 删除;
--     api_type 保留(枚举含文本对话,同时服务文本)。ia_ai_model 去掉
--     comfyui_workflow_id(ComfyUI 图像/视频工作流绑定列);model_type、
--     support_vision、multimodal_input_*、capability_preset_code 等字段同时服务
--     文本模型(多模态输入/能力预设),全部保留。
--   * 融光 afv_api_config.app_id(平台侧应用ID,如 Vertex AI)与本方案多应用列
--     app_id(BIGINT)重名,改名 platform_app_id 保留,避免语义冲突。
--   * tinyint(0/1) -> BOOLEAN;json -> JSONB;MEDIUMTEXT -> TEXT。
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. ia_app:应用注册表(新增;单应用部署预置 default 应用 id=1)
-- ---------------------------------------------------------------------
CREATE TABLE ia_app (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_key                     VARCHAR(64)  NOT NULL,
    name                        VARCHAR(128) NOT NULL,
    sign_public_key             TEXT,
    webhook_url                 VARCHAR(512),
    webhook_secret              VARCHAR(512),
    conversation_retention_days INT          NOT NULL DEFAULT 180,
    status                      INT          NOT NULL DEFAULT 1,
    deleted                     BOOLEAN      NOT NULL DEFAULT FALSE,
    create_time                 TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time                 TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ia_app_key UNIQUE (app_key)
);

COMMENT ON TABLE ia_app IS '应用注册表(宿主应用;多应用共享部署的命名空间,ADR-10)';
COMMENT ON COLUMN ia_app.id IS '主键ID(即各业务表 app_id)';
COMMENT ON COLUMN ia_app.app_key IS '应用唯一标识(embed token 与 SDK 初始化使用)';
COMMENT ON COLUMN ia_app.name IS '应用名称';
COMMENT ON COLUMN ia_app.sign_public_key IS '宿主应用签名公钥(PEM;embed token 验签)';
COMMENT ON COLUMN ia_app.webhook_url IS '终态通知 Webhook 回调地址';
COMMENT ON COLUMN ia_app.webhook_secret IS 'Webhook 回调签名密钥';
COMMENT ON COLUMN ia_app.conversation_retention_days IS '会话保留天数(超期清理,默认 180)';
COMMENT ON COLUMN ia_app.status IS '状态:0-禁用 1-启用';
COMMENT ON COLUMN ia_app.deleted IS '逻辑删除标志';
COMMENT ON COLUMN ia_app.create_time IS '创建时间';
COMMENT ON COLUMN ia_app.update_time IS '更新时间';

-- 预置默认应用:app_id 列 DEFAULT 1 即指向该行(单应用部署固定使用)
INSERT INTO ia_app (app_key, name, status)
VALUES ('default', '默认应用', 1);

-- ---------------------------------------------------------------------
-- 2. ia_tool_registry:应用工具注册表(新增;MCP 工具清单快照与治理策略)
-- ---------------------------------------------------------------------
CREATE TABLE ia_tool_registry (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id            BIGINT       NOT NULL DEFAULT 1,
    server_key        VARCHAR(64)  NOT NULL,
    tool_name         VARCHAR(128) NOT NULL,
    fqn               VARCHAR(200) NOT NULL,
    description       VARCHAR(1024),
    parameters_schema TEXT,
    annotations_json  TEXT,
    risk_level        VARCHAR(16)  NOT NULL DEFAULT 'HIGH',
    admin_policy      VARCHAR(16),
    resume_safe       BOOLEAN      NOT NULL DEFAULT FALSE,
    concurrency_safe  BOOLEAN      NOT NULL DEFAULT FALSE,
    source            VARCHAR(16)  NOT NULL,
    endpoint_url      VARCHAR(2048),
    credentials_enc   TEXT,
    schema_sha256     CHAR(64),
    enabled           BOOLEAN      NOT NULL DEFAULT TRUE,
    last_test_status  VARCHAR(32),
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    create_time       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ia_tool_registry_fqn UNIQUE (app_id, fqn)
);

CREATE INDEX idx_ia_tool_registry_server
    ON ia_tool_registry (app_id, server_key);

COMMENT ON TABLE ia_tool_registry IS '应用工具注册表(MCP 工具清单快照、风险级与治理策略)';
COMMENT ON COLUMN ia_tool_registry.id IS '主键ID';
COMMENT ON COLUMN ia_tool_registry.app_id IS '所属应用;单应用部署固定为 1,P1 接入 AppContext 后显式写入';
COMMENT ON COLUMN ia_tool_registry.server_key IS 'MCP 服务标识(应用内唯一,注销时级联清除注册与授权)';
COMMENT ON COLUMN ia_tool_registry.tool_name IS '工具名(MCP tools/list 返回的 name)';
COMMENT ON COLUMN ia_tool_registry.fqn IS '工具全限定名(server_key + ''.'' + tool_name,应用内唯一)';
COMMENT ON COLUMN ia_tool_registry.description IS '工具描述(MCP 工具注解原文)';
COMMENT ON COLUMN ia_tool_registry.parameters_schema IS '入参 JSON Schema 快照(锁定用)';
COMMENT ON COLUMN ia_tool_registry.annotations_json IS 'MCP 工具注解 JSON(readOnlyHint/destructiveHint 等,用于生成默认风险级)';
COMMENT ON COLUMN ia_tool_registry.risk_level IS '风险等级:low/medium/high;注册时注解生成默认值+人工覆盖,未评估默认 high';
COMMENT ON COLUMN ia_tool_registry.admin_policy IS '管理员策略:force-ask/force-allow/deny;NULL-不强制';
COMMENT ON COLUMN ia_tool_registry.resume_safe IS '确认暂停后恢复运行是否安全(副作用工具为 FALSE)';
COMMENT ON COLUMN ia_tool_registry.concurrency_safe IS '是否并发安全(并发守卫放行依据)';
COMMENT ON COLUMN ia_tool_registry.source IS '工具来源:host_app/third_party/builtin';
COMMENT ON COLUMN ia_tool_registry.endpoint_url IS '三方 MCP 端点地址(host_app 工具经宿主桥暴露时为空)';
COMMENT ON COLUMN ia_tool_registry.credentials_enc IS '三方 MCP 凭证(加密存储)';
COMMENT ON COLUMN ia_tool_registry.schema_sha256 IS '工具清单快照 SHA-256(schema 变更检测与授权失效)';
COMMENT ON COLUMN ia_tool_registry.enabled IS '是否启用:TRUE-启用 FALSE-停用(紧急停用入口)';
COMMENT ON COLUMN ia_tool_registry.last_test_status IS '最近一次工具体检/连通性测试结果';
COMMENT ON COLUMN ia_tool_registry.deleted IS '逻辑删除标志';
COMMENT ON COLUMN ia_tool_registry.create_time IS '创建时间';
COMMENT ON COLUMN ia_tool_registry.update_time IS '更新时间';

-- ---------------------------------------------------------------------
-- 3. ia_tool_grant:用户工具授权表(新增;会话级/永久授权)
-- ---------------------------------------------------------------------
CREATE TABLE ia_tool_grant (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id         BIGINT       NOT NULL DEFAULT 1,
    tenant_id      BIGINT       NOT NULL DEFAULT 0,
    user_id        BIGINT       NOT NULL,
    tool_fqn       VARCHAR(200) NOT NULL,
    scope          VARCHAR(16)  NOT NULL,
    conversation_id BIGINT,
    risk_at_grant  VARCHAR(16),
    schema_sha256  CHAR(64),
    source         VARCHAR(16),
    deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    create_time    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- conversation_id 在永久授权(scope=permanent)时为 NULL,
    -- NULLS NOT DISTINCT 保证同一用户对同一工具的永久授权唯一
    CONSTRAINT uk_ia_tool_grant UNIQUE NULLS NOT DISTINCT
        (app_id, user_id, tool_fqn, scope, conversation_id)
);

COMMENT ON TABLE ia_tool_grant IS '用户工具授权表(会话级/永久;风险升级或 schema 变更自动失效)';
COMMENT ON COLUMN ia_tool_grant.id IS '主键ID';
COMMENT ON COLUMN ia_tool_grant.app_id IS '所属应用;单应用部署固定为 1,P1 接入 AppContext 后显式写入';
COMMENT ON COLUMN ia_tool_grant.tenant_id IS '所属租户(团队)ID';
COMMENT ON COLUMN ia_tool_grant.user_id IS '被授权用户ID';
COMMENT ON COLUMN ia_tool_grant.tool_fqn IS '工具全限定名(ia_tool_registry.fqn)';
COMMENT ON COLUMN ia_tool_grant.scope IS '授权作用域:conversation-仅本会话 permanent-永久';
COMMENT ON COLUMN ia_tool_grant.conversation_id IS '会话ID(ia_agent_conversation.id;scope=permanent 时为 NULL)';
COMMENT ON COLUMN ia_tool_grant.risk_at_grant IS '授予时工具风险等级快照';
COMMENT ON COLUMN ia_tool_grant.schema_sha256 IS '授予时工具清单 SHA-256 快照(变更检测)';
COMMENT ON COLUMN ia_tool_grant.source IS '授权来源:live-confirm(确认流)/admin 等';
COMMENT ON COLUMN ia_tool_grant.deleted IS '逻辑删除标志(撤销授权)';
COMMENT ON COLUMN ia_tool_grant.create_time IS '创建时间';
COMMENT ON COLUMN ia_tool_grant.update_time IS '更新时间';

-- ---------------------------------------------------------------------
-- 4. ia_audit_log:工具审计日志表(新增;仅追加 append-only)
-- ---------------------------------------------------------------------
CREATE TABLE ia_audit_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id          BIGINT       NOT NULL DEFAULT 1,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    user_id         BIGINT,
    conversation_id BIGINT,
    run_id          VARCHAR(64),
    tool_fqn        VARCHAR(200),
    decision        VARCHAR(16)  NOT NULL,
    decision_source VARCHAR(24)  NOT NULL,
    risk_level      VARCHAR(16),
    params_masked_json TEXT,
    result_summary  TEXT,
    error_text      TEXT,
    duration_ms     BIGINT,
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ia_audit_log IS '工具调用审计日志表(仅追加,不提供更新/删除;敏感参数只存脱敏值)';
COMMENT ON COLUMN ia_audit_log.id IS '主键ID';
COMMENT ON COLUMN ia_audit_log.app_id IS '所属应用;单应用部署固定为 1,P1 接入 AppContext 后显式写入';
COMMENT ON COLUMN ia_audit_log.tenant_id IS '所属租户(团队)ID';
COMMENT ON COLUMN ia_audit_log.user_id IS '发起用户ID';
COMMENT ON COLUMN ia_audit_log.conversation_id IS '会话ID(ia_agent_conversation.id)';
COMMENT ON COLUMN ia_audit_log.run_id IS '运行ID(ia_agent_run.run_id)';
COMMENT ON COLUMN ia_audit_log.tool_fqn IS '工具全限定名';
COMMENT ON COLUMN ia_audit_log.decision IS '裁决结果:allowed-放行 denied-拒绝';
COMMENT ON COLUMN ia_audit_log.decision_source IS '裁决来源:mode-default/user-grant/forced-policy/live-confirm/full-access';
COMMENT ON COLUMN ia_audit_log.risk_level IS '裁决时工具风险等级';
COMMENT ON COLUMN ia_audit_log.params_masked_json IS '工具入参(敏感字段脱敏后 JSON)';
COMMENT ON COLUMN ia_audit_log.result_summary IS '执行结果摘要';
COMMENT ON COLUMN ia_audit_log.error_text IS '失败错误信息';
COMMENT ON COLUMN ia_audit_log.duration_ms IS '工具执行耗时(毫秒)';
COMMENT ON COLUMN ia_audit_log.create_time IS '创建时间(append-only,无更新/删除)';

CREATE INDEX idx_ia_audit_log_app_time
    ON ia_audit_log (app_id, create_time);
CREATE INDEX idx_ia_audit_log_app_conversation
    ON ia_audit_log (app_id, conversation_id);
CREATE INDEX idx_ia_audit_log_app_run
    ON ia_audit_log (app_id, run_id);

-- ---------------------------------------------------------------------
-- 5. ia_model_api_config:模型接入配置表(源:afv_api_config,文本部分)
-- ---------------------------------------------------------------------
CREATE TABLE ia_model_api_config (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id             BIGINT       NOT NULL DEFAULT 1,
    name               VARCHAR(128) NOT NULL,
    platform           VARCHAR(32),
    text_protocol      VARCHAR(64),
    api_type           INT,
    api_url            VARCHAR(512),
    auto_append_v1_path BOOLEAN     NOT NULL DEFAULT TRUE,
    proxy_type         VARCHAR(16),
    proxy_host         VARCHAR(255),
    proxy_port         INT,
    proxy_username     VARCHAR(255),
    proxy_password     VARCHAR(255),
    api_key            VARCHAR(512),
    platform_app_id    VARCHAR(128),
    app_secret         TEXT,
    model_id           BIGINT,
    status             INT          NOT NULL DEFAULT 1,
    remark             VARCHAR(1024),
    deleted            BOOLEAN      NOT NULL DEFAULT FALSE,
    create_time        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ia_model_api_config IS '模型接入配置表(移植自融光 afv_api_config,去除图像/视频协议列)';
COMMENT ON COLUMN ia_model_api_config.id IS '主键ID';
COMMENT ON COLUMN ia_model_api_config.app_id IS '所属应用;单应用部署固定为 1,P1 接入 AppContext 后显式写入';
COMMENT ON COLUMN ia_model_api_config.name IS '配置名称';
COMMENT ON COLUMN ia_model_api_config.platform IS '平台标识:deepseek/dashscope/openai_compatible/ollama/anthropic/vertex_ai 等';
COMMENT ON COLUMN ia_model_api_config.text_protocol IS '文本模型默认请求协议';
COMMENT ON COLUMN ia_model_api_config.api_type IS 'API类型:1-文本对话(2-图片生成/3-视频生成列已裁剪,InnerAgent 仅文本)';
COMMENT ON COLUMN ia_model_api_config.api_url IS 'API接口地址';
COMMENT ON COLUMN ia_model_api_config.auto_append_v1_path IS 'OpenAI兼容请求是否自动补充 /v1 路径';
COMMENT ON COLUMN ia_model_api_config.proxy_type IS '出站代理类型:none/http/socks5';
COMMENT ON COLUMN ia_model_api_config.proxy_host IS '出站代理主机';
COMMENT ON COLUMN ia_model_api_config.proxy_port IS '出站代理端口';
COMMENT ON COLUMN ia_model_api_config.proxy_username IS '出站代理认证用户名';
COMMENT ON COLUMN ia_model_api_config.proxy_password IS '出站代理认证密码';
COMMENT ON COLUMN ia_model_api_config.api_key IS 'API密钥';
COMMENT ON COLUMN ia_model_api_config.platform_app_id IS '平台侧应用ID(部分平台需要;融光原名 app_id,因多应用列改名)';
COMMENT ON COLUMN ia_model_api_config.app_secret IS '应用密钥/服务账号 JSON Key(部分平台需要,如 Vertex AI Service Account)';
COMMENT ON COLUMN ia_model_api_config.model_id IS '关联模型ID(ia_ai_model.id)';
COMMENT ON COLUMN ia_model_api_config.status IS '状态:0-禁用 1-启用';
COMMENT ON COLUMN ia_model_api_config.remark IS '备注说明';
COMMENT ON COLUMN ia_model_api_config.deleted IS '逻辑删除标志';
COMMENT ON COLUMN ia_model_api_config.create_time IS '创建时间';
COMMENT ON COLUMN ia_model_api_config.update_time IS '更新时间';

-- ---------------------------------------------------------------------
-- 6. ia_ai_model:AI 模型表(源:afv_ai_model,文本部分)
-- ---------------------------------------------------------------------
CREATE TABLE ia_ai_model (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id                      BIGINT       NOT NULL DEFAULT 1,
    name                        VARCHAR(128) NOT NULL,
    code                        VARCHAR(64)  NOT NULL,
    model_protocol              VARCHAR(64),
    capability_preset_code      VARCHAR(128),
    model_type                  INT          NOT NULL,
    icon                        VARCHAR(512),
    description                 VARCHAR(1024),
    sort                        INT          DEFAULT 0,
    status                      INT          NOT NULL DEFAULT 1,
    config                      TEXT,
    default_model               BOOLEAN      DEFAULT FALSE,
    max_concurrency             INT          DEFAULT 5,
    api_config_id               BIGINT,
    support_vision              BOOLEAN      DEFAULT FALSE,
    multimodal_input_types      JSONB        NOT NULL DEFAULT '[]'::jsonb,
    multimodal_input_transports JSONB        NOT NULL DEFAULT '{}'::jsonb,
    support_reasoning           BOOLEAN      DEFAULT FALSE,
    reasoning_effort_levels     JSONB        NOT NULL DEFAULT '[]'::jsonb,
    context_window              INT,
    deleted                     BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_id                  BIGINT       NOT NULL DEFAULT 0,
    create_time                 TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time                 TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ia_ai_model_api_code UNIQUE (api_config_id, code, deleted_id)
);

COMMENT ON TABLE ia_ai_model IS 'AI模型表(移植自融光 afv_ai_model;剔除 comfyui_workflow_id 图像/视频绑定列)';
COMMENT ON COLUMN ia_ai_model.id IS '主键ID';
COMMENT ON COLUMN ia_ai_model.app_id IS '所属应用;单应用部署固定为 1,P1 接入 AppContext 后显式写入';
COMMENT ON COLUMN ia_ai_model.name IS '模型显示名称';
COMMENT ON COLUMN ia_ai_model.code IS '模型代码标识(如 deepseek-chat、qwen-max)';
COMMENT ON COLUMN ia_ai_model.model_protocol IS '模型级请求协议覆盖;为空时继承接入配置默认协议';
COMMENT ON COLUMN ia_ai_model.capability_preset_code IS '模型能力预设代码;NULL 表示自定义能力配置(同时服务文本模型,保留)';
COMMENT ON COLUMN ia_ai_model.model_type IS '模型类型:1-文本对话(2-图片生成/3-视频生成不再新增,列保留兼容枚举)';
COMMENT ON COLUMN ia_ai_model.icon IS '模型图标URL';
COMMENT ON COLUMN ia_ai_model.description IS '模型描述说明';
COMMENT ON COLUMN ia_ai_model.sort IS '排列顺序';
COMMENT ON COLUMN ia_ai_model.status IS '状态:0-禁用 1-启用';
COMMENT ON COLUMN ia_ai_model.config IS '模型特定配置JSON(temperature、top_p 等)';
COMMENT ON COLUMN ia_ai_model.default_model IS '是否为默认模型';
COMMENT ON COLUMN ia_ai_model.max_concurrency IS '最大并发请求数';
COMMENT ON COLUMN ia_ai_model.api_config_id IS '关联接入配置ID(ia_model_api_config.id)';
COMMENT ON COLUMN ia_ai_model.support_vision IS '是否支持视觉理解(文本对话传图,保留)';
COMMENT ON COLUMN ia_ai_model.multimodal_input_types IS '支持的多模态输入类型:image/video/audio/file';
COMMENT ON COLUMN ia_ai_model.multimodal_input_transports IS '各输入类型支持的传输方式:url/base64';
COMMENT ON COLUMN ia_ai_model.support_reasoning IS '是否支持深度思考(reasoning)';
COMMENT ON COLUMN ia_ai_model.reasoning_effort_levels IS '思考等级列表,按能力从高到低排序';
COMMENT ON COLUMN ia_ai_model.context_window IS '上下文窗口大小(token 数)';
COMMENT ON COLUMN ia_ai_model.deleted IS '逻辑删除标志';
COMMENT ON COLUMN ia_ai_model.deleted_id IS '逻辑删除隔离标识:0-未删除,删除后为记录ID(避免唯一索引占用)';
COMMENT ON COLUMN ia_ai_model.create_time IS '创建时间';
COMMENT ON COLUMN ia_ai_model.update_time IS '更新时间';
