-- =====================================================================
-- InnerAgent V3:Agent 状态存储 / 工作区 / 用户自定义 MCP
-- 移植自融光 ai-fusion-video 迁移(列定义逐一对照):
--   * V1.1.0.0.7__agent_state_store.sql(afv_agent_state)
--   * V1.1.0.0.8__agent_state_retention.sql(afv_agent_state_cleanup_policy)
--   * V1.1.0.0.3__agent_workspace_and_user_mcp.sql(afv_agent_workspace_* / afv_agent_mcp_server)
-- 改造规则:
--   * MySQL 8 -> PostgreSQL 17 方言;afv_ 前缀 -> ia_ 前缀;所有业务表增加
--     app_id BIGINT NOT NULL DEFAULT 1(所属应用;单应用部署固定为 1,
--     P1 接入 AppContext 后显式写入;ia_agent_state 由内核 JDBC 直写,
--     INSERT 不携带 app_id,依赖默认值)。
--   * 实体继承 TenantBaseEntity 的表保留 tenant_id(mcp_server 与 workspace 三表);
--     ia_agent_state / ia_agent_state_cleanup_policy / ia_agent_workspace_config
--     实体无租户字段(策略行/单例配置/JDBC 直写),不加 tenant_id。
--   * LONGTEXT -> TEXT;bit(1) -> BOOLEAN;DATETIME -> TIMESTAMP。
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. ia_agent_state:AgentState 状态存储表(内核 JdbcTemplate 直写)
-- ---------------------------------------------------------------------
CREATE TABLE ia_agent_state (
    app_id      BIGINT       NOT NULL DEFAULT 1,
    session_id  VARCHAR(255) NOT NULL,
    state_key   VARCHAR(255) NOT NULL,
    item_index  INT          NOT NULL DEFAULT 0,
    state_data  TEXT         NOT NULL,
    created_at  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (session_id, state_key, item_index)
);

CREATE INDEX idx_ia_agent_state_updated_at
    ON ia_agent_state (updated_at);

COMMENT ON TABLE ia_agent_state IS 'AgentState 状态存储表(AgentScope 内核会话状态,键值条目)';
COMMENT ON COLUMN ia_agent_state.app_id IS '所属应用;单应用部署固定为 1(内核 JDBC 直写,依赖默认值)';
COMMENT ON COLUMN ia_agent_state.session_id IS '状态会话ID(含用户/租户命名空间前缀)';
COMMENT ON COLUMN ia_agent_state.state_key IS '状态键';
COMMENT ON COLUMN ia_agent_state.item_index IS '同键多值条目下标(从 0 开始)';
COMMENT ON COLUMN ia_agent_state.state_data IS '状态正文(JSON)';
COMMENT ON COLUMN ia_agent_state.created_at IS '创建时间';
COMMENT ON COLUMN ia_agent_state.updated_at IS '更新时间';

-- ---------------------------------------------------------------------
-- 2. ia_agent_state_cleanup_policy:AgentState 清理策略表(单例 id=1)
-- ---------------------------------------------------------------------
CREATE TABLE ia_agent_state_cleanup_policy (
    id                     BIGINT       PRIMARY KEY,
    app_id                 BIGINT       NOT NULL DEFAULT 1,
    cleanup_interval_days  INT          NOT NULL DEFAULT 1,
    retention_days         INT          NOT NULL DEFAULT 30,
    next_cleanup_at        TIMESTAMP(3) NOT NULL,
    cleanup_lease_owner    VARCHAR(160),
    cleanup_lease_until    TIMESTAMP(3),
    last_cleanup_at        TIMESTAMP(3),
    create_time            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_ia_agent_state_cleanup_interval
        CHECK (cleanup_interval_days BETWEEN 1 AND 365),
    CONSTRAINT chk_ia_agent_state_retention_days
        CHECK (retention_days BETWEEN 1 AND 3650)
);

COMMENT ON TABLE ia_agent_state_cleanup_policy IS 'AgentState 清理策略表(单例行 id=1)';
COMMENT ON COLUMN ia_agent_state_cleanup_policy.id IS '主键ID(固定为 1 的单例行)';
COMMENT ON COLUMN ia_agent_state_cleanup_policy.app_id IS '所属应用;单应用部署固定为 1,P1 接入 AppContext 后显式写入';
COMMENT ON COLUMN ia_agent_state_cleanup_policy.cleanup_interval_days IS '清理扫描间隔(天,1-365)';
COMMENT ON COLUMN ia_agent_state_cleanup_policy.retention_days IS '状态保留天数(1-3650)';
COMMENT ON COLUMN ia_agent_state_cleanup_policy.next_cleanup_at IS '下次清理时间';
COMMENT ON COLUMN ia_agent_state_cleanup_policy.cleanup_lease_owner IS '清理任务租约持有者';
COMMENT ON COLUMN ia_agent_state_cleanup_policy.cleanup_lease_until IS '清理任务租约到期时间';
COMMENT ON COLUMN ia_agent_state_cleanup_policy.last_cleanup_at IS '最近一次清理时间';
COMMENT ON COLUMN ia_agent_state_cleanup_policy.create_time IS '创建时间';
COMMENT ON COLUMN ia_agent_state_cleanup_policy.update_time IS '更新时间';

INSERT INTO ia_agent_state_cleanup_policy
    (id, cleanup_interval_days, retention_days, next_cleanup_at)
VALUES
    (1, 1, 30, CURRENT_TIMESTAMP);

-- ---------------------------------------------------------------------
-- 3. ia_agent_mcp_server:用户自定义 MCP 服务表
-- ---------------------------------------------------------------------
CREATE TABLE ia_agent_mcp_server (
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id                         BIGINT       NOT NULL DEFAULT 1,
    tenant_id                      BIGINT       NOT NULL DEFAULT 0,
    user_id                        BIGINT       NOT NULL,
    name                           VARCHAR(128) NOT NULL,
    transport                      VARCHAR(32)  NOT NULL,
    url                            VARCHAR(2048) NOT NULL,
    headers_json                   TEXT,
    query_params_json              TEXT,
    enabled_tools_json             TEXT,
    protocol_versions_json         TEXT,
    timeout_seconds                INT          NOT NULL DEFAULT 120,
    initialization_timeout_seconds INT          NOT NULL DEFAULT 30,
    status                         INT          NOT NULL DEFAULT 1,
    last_test_status               VARCHAR(32),
    last_test_message              VARCHAR(1024),
    deleted                        BOOLEAN      NOT NULL DEFAULT FALSE,
    create_time                    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time                    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ia_agent_mcp_user_status
    ON ia_agent_mcp_server (user_id, status, id);

COMMENT ON TABLE ia_agent_mcp_server IS '用户自定义 MCP 服务表(用户级自接 MCP)';
COMMENT ON COLUMN ia_agent_mcp_server.id IS '主键ID';
COMMENT ON COLUMN ia_agent_mcp_server.app_id IS '所属应用;单应用部署固定为 1,P1 接入 AppContext 后显式写入';
COMMENT ON COLUMN ia_agent_mcp_server.tenant_id IS '所属租户(团队)ID';
COMMENT ON COLUMN ia_agent_mcp_server.user_id IS '所属用户(仅本人可用)';
COMMENT ON COLUMN ia_agent_mcp_server.name IS '服务名称';
COMMENT ON COLUMN ia_agent_mcp_server.transport IS '传输方式:http/sse';
COMMENT ON COLUMN ia_agent_mcp_server.url IS 'MCP 地址';
COMMENT ON COLUMN ia_agent_mcp_server.headers_json IS '请求头 JSON';
COMMENT ON COLUMN ia_agent_mcp_server.query_params_json IS '查询参数 JSON';
COMMENT ON COLUMN ia_agent_mcp_server.enabled_tools_json IS '启用工具 JSON';
COMMENT ON COLUMN ia_agent_mcp_server.protocol_versions_json IS '协议版本 JSON';
COMMENT ON COLUMN ia_agent_mcp_server.timeout_seconds IS '工具调用超时(秒)';
COMMENT ON COLUMN ia_agent_mcp_server.initialization_timeout_seconds IS '初始化超时(秒)';
COMMENT ON COLUMN ia_agent_mcp_server.status IS '状态:0-禁用 1-启用';
COMMENT ON COLUMN ia_agent_mcp_server.last_test_status IS '最近一次连通性测试结果';
COMMENT ON COLUMN ia_agent_mcp_server.last_test_message IS '最近一次连通性测试消息';
COMMENT ON COLUMN ia_agent_mcp_server.deleted IS '逻辑删除标志';
COMMENT ON COLUMN ia_agent_mcp_server.create_time IS '创建时间';
COMMENT ON COLUMN ia_agent_mcp_server.update_time IS '更新时间';

-- ---------------------------------------------------------------------
-- 4. ia_agent_workspace_config:智能体工作空间配置表(单例 id=1)
-- ---------------------------------------------------------------------
CREATE TABLE ia_agent_workspace_config (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id               BIGINT      NOT NULL DEFAULT 1,
    backend_type         VARCHAR(32) NOT NULL DEFAULT 'database',
    storage_config_id    BIGINT,
    local_path           VARCHAR(512),
    migration_status     VARCHAR(32) NOT NULL DEFAULT 'idle',
    active_migration_id  BIGINT,
    deleted              BOOLEAN     NOT NULL DEFAULT FALSE,
    create_time          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ia_agent_workspace_storage_config
    ON ia_agent_workspace_config (storage_config_id);

COMMENT ON TABLE ia_agent_workspace_config IS '智能体工作空间配置表(单例行 id=1)';
COMMENT ON COLUMN ia_agent_workspace_config.id IS '主键ID(固定为 1 的单例行)';
COMMENT ON COLUMN ia_agent_workspace_config.app_id IS '所属应用;单应用部署固定为 1,P1 接入 AppContext 后显式写入';
COMMENT ON COLUMN ia_agent_workspace_config.backend_type IS '工作空间后端类型:database/local/object_storage';
COMMENT ON COLUMN ia_agent_workspace_config.storage_config_id IS '对象存储配置 ID(后端为 object_storage 时)';
COMMENT ON COLUMN ia_agent_workspace_config.local_path IS '本地工作空间根目录(后端为 local 时)';
COMMENT ON COLUMN ia_agent_workspace_config.migration_status IS '工作空间迁移状态:idle/copying/verifying/cutover/failed';
COMMENT ON COLUMN ia_agent_workspace_config.active_migration_id IS '当前迁移任务 ID(ia_agent_workspace_migration.id)';
COMMENT ON COLUMN ia_agent_workspace_config.deleted IS '逻辑删除标志';
COMMENT ON COLUMN ia_agent_workspace_config.create_time IS '创建时间';
COMMENT ON COLUMN ia_agent_workspace_config.update_time IS '更新时间';

INSERT INTO ia_agent_workspace_config (backend_type, migration_status)
VALUES ('database', 'idle');

-- ---------------------------------------------------------------------
-- 5. ia_agent_workspace_entry:智能体工作空间条目表
-- ---------------------------------------------------------------------
CREATE TABLE ia_agent_workspace_entry (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id            BIGINT       NOT NULL DEFAULT 1,
    tenant_id         BIGINT       NOT NULL DEFAULT 0,
    namespace_hash    CHAR(64)     NOT NULL,
    namespace_key     VARCHAR(1024) NOT NULL,
    item_hash         CHAR(64)     NOT NULL,
    item_key          VARCHAR(2048) NOT NULL,
    backend_type      VARCHAR(32)  NOT NULL,
    storage_config_id BIGINT,
    local_path        VARCHAR(512),
    content_ref       VARCHAR(1024),
    payload           TEXT,
    content_sha256    CHAR(64)     NOT NULL,
    content_size      BIGINT       NOT NULL DEFAULT 0,
    version           BIGINT       NOT NULL DEFAULT 1,
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    create_time       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ia_agent_workspace_entry UNIQUE (namespace_hash, item_hash, deleted)
);

CREATE INDEX idx_ia_agent_workspace_namespace
    ON ia_agent_workspace_entry (namespace_hash, id);
CREATE INDEX idx_ia_agent_workspace_backend
    ON ia_agent_workspace_entry (backend_type, storage_config_id);

COMMENT ON TABLE ia_agent_workspace_entry IS '智能体工作空间条目表(AgentScope 文件工作区条目)';
COMMENT ON COLUMN ia_agent_workspace_entry.id IS '主键ID';
COMMENT ON COLUMN ia_agent_workspace_entry.app_id IS '所属应用;单应用部署固定为 1,P1 接入 AppContext 后显式写入';
COMMENT ON COLUMN ia_agent_workspace_entry.tenant_id IS '所属租户(团队)ID';
COMMENT ON COLUMN ia_agent_workspace_entry.namespace_hash IS '命名空间 SHA-256';
COMMENT ON COLUMN ia_agent_workspace_entry.namespace_key IS 'AgentScope 命名空间';
COMMENT ON COLUMN ia_agent_workspace_entry.item_hash IS '文件键 SHA-256';
COMMENT ON COLUMN ia_agent_workspace_entry.item_key IS '工作空间文件键';
COMMENT ON COLUMN ia_agent_workspace_entry.backend_type IS '正文所在后端:database/local/object_storage';
COMMENT ON COLUMN ia_agent_workspace_entry.storage_config_id IS '正文所在对象存储配置 ID';
COMMENT ON COLUMN ia_agent_workspace_entry.local_path IS '正文所在本地存储根目录';
COMMENT ON COLUMN ia_agent_workspace_entry.content_ref IS '本地相对路径或对象键';
COMMENT ON COLUMN ia_agent_workspace_entry.payload IS '数据库后端正文(JSON)';
COMMENT ON COLUMN ia_agent_workspace_entry.content_sha256 IS '正文 SHA-256';
COMMENT ON COLUMN ia_agent_workspace_entry.content_size IS '正文字节数';
COMMENT ON COLUMN ia_agent_workspace_entry.version IS 'CAS 乐观锁版本';
COMMENT ON COLUMN ia_agent_workspace_entry.deleted IS '逻辑删除标志';
COMMENT ON COLUMN ia_agent_workspace_entry.create_time IS '创建时间';
COMMENT ON COLUMN ia_agent_workspace_entry.update_time IS '更新时间';

-- ---------------------------------------------------------------------
-- 6. ia_agent_workspace_migration:智能体工作空间迁移任务表
-- ---------------------------------------------------------------------
CREATE TABLE ia_agent_workspace_migration (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id                   BIGINT      NOT NULL DEFAULT 1,
    tenant_id                BIGINT      NOT NULL DEFAULT 0,
    source_backend_type      VARCHAR(32) NOT NULL,
    source_storage_config_id BIGINT,
    source_local_path        VARCHAR(512),
    target_backend_type      VARCHAR(32) NOT NULL,
    target_storage_config_id BIGINT,
    target_local_path        VARCHAR(512),
    status                   VARCHAR(32) NOT NULL,
    total_count              BIGINT      NOT NULL DEFAULT 0,
    copied_count             BIGINT      NOT NULL DEFAULT 0,
    failed_count             BIGINT      NOT NULL DEFAULT 0,
    error_message            TEXT,
    started_at               TIMESTAMP,
    finished_at              TIMESTAMP,
    deleted                  BOOLEAN     NOT NULL DEFAULT FALSE,
    create_time              TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time              TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ia_agent_workspace_migration_status
    ON ia_agent_workspace_migration (status, id);

COMMENT ON TABLE ia_agent_workspace_migration IS '智能体工作空间迁移任务表(后端间搬迁)';
COMMENT ON COLUMN ia_agent_workspace_migration.id IS '主键ID';
COMMENT ON COLUMN ia_agent_workspace_migration.app_id IS '所属应用;单应用部署固定为 1,P1 接入 AppContext 后显式写入';
COMMENT ON COLUMN ia_agent_workspace_migration.tenant_id IS '所属租户(团队)ID';
COMMENT ON COLUMN ia_agent_workspace_migration.source_backend_type IS '源后端类型:database/local/object_storage';
COMMENT ON COLUMN ia_agent_workspace_migration.source_storage_config_id IS '源对象存储配置 ID';
COMMENT ON COLUMN ia_agent_workspace_migration.source_local_path IS '源本地存储根目录';
COMMENT ON COLUMN ia_agent_workspace_migration.target_backend_type IS '目标后端类型:database/local/object_storage';
COMMENT ON COLUMN ia_agent_workspace_migration.target_storage_config_id IS '目标对象存储配置 ID';
COMMENT ON COLUMN ia_agent_workspace_migration.target_local_path IS '目标本地存储根目录';
COMMENT ON COLUMN ia_agent_workspace_migration.status IS '迁移状态:copying/verifying/cutover/completed/failed/rolled_back';
COMMENT ON COLUMN ia_agent_workspace_migration.total_count IS '迁移条目总数';
COMMENT ON COLUMN ia_agent_workspace_migration.copied_count IS '已拷贝条目数';
COMMENT ON COLUMN ia_agent_workspace_migration.failed_count IS '失败条目数';
COMMENT ON COLUMN ia_agent_workspace_migration.error_message IS '失败错误信息';
COMMENT ON COLUMN ia_agent_workspace_migration.started_at IS '开始时间';
COMMENT ON COLUMN ia_agent_workspace_migration.finished_at IS '结束时间';
COMMENT ON COLUMN ia_agent_workspace_migration.deleted IS '逻辑删除标志';
COMMENT ON COLUMN ia_agent_workspace_migration.create_time IS '创建时间';
COMMENT ON COLUMN ia_agent_workspace_migration.update_time IS '更新时间';

-- ---------------------------------------------------------------------
-- 7. ia_agent_workspace_migration_item:智能体工作空间迁移明细表
-- ---------------------------------------------------------------------
CREATE TABLE ia_agent_workspace_migration_item (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id                   BIGINT      NOT NULL DEFAULT 1,
    tenant_id                BIGINT      NOT NULL DEFAULT 0,
    migration_id             BIGINT      NOT NULL,
    entry_id                 BIGINT      NOT NULL,
    source_backend_type      VARCHAR(32) NOT NULL,
    source_storage_config_id BIGINT,
    source_local_path        VARCHAR(512),
    source_content_ref       VARCHAR(1024),
    source_payload           TEXT,
    target_backend_type      VARCHAR(32) NOT NULL,
    target_storage_config_id BIGINT,
    target_local_path        VARCHAR(512),
    target_content_ref       VARCHAR(1024),
    target_payload           TEXT,
    content_sha256           CHAR(64)    NOT NULL,
    content_size             BIGINT      NOT NULL DEFAULT 0,
    status                   VARCHAR(32) NOT NULL DEFAULT 'copied',
    deleted                  BOOLEAN     NOT NULL DEFAULT FALSE,
    create_time              TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time              TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ia_agent_workspace_migration_item UNIQUE (migration_id, entry_id, deleted)
);

CREATE INDEX idx_ia_agent_workspace_migration_item_entry
    ON ia_agent_workspace_migration_item (entry_id);

COMMENT ON TABLE ia_agent_workspace_migration_item IS '智能体工作空间迁移明细表(逐条目迁移进度与快照)';
COMMENT ON COLUMN ia_agent_workspace_migration_item.id IS '主键ID';
COMMENT ON COLUMN ia_agent_workspace_migration_item.app_id IS '所属应用;单应用部署固定为 1,P1 接入 AppContext 后显式写入';
COMMENT ON COLUMN ia_agent_workspace_migration_item.tenant_id IS '所属租户(团队)ID';
COMMENT ON COLUMN ia_agent_workspace_migration_item.migration_id IS '所属迁移任务ID(ia_agent_workspace_migration.id)';
COMMENT ON COLUMN ia_agent_workspace_migration_item.entry_id IS '工作空间条目ID(ia_agent_workspace_entry.id)';
COMMENT ON COLUMN ia_agent_workspace_migration_item.source_backend_type IS '源后端类型';
COMMENT ON COLUMN ia_agent_workspace_migration_item.source_storage_config_id IS '源对象存储配置 ID';
COMMENT ON COLUMN ia_agent_workspace_migration_item.source_local_path IS '源本地存储根目录';
COMMENT ON COLUMN ia_agent_workspace_migration_item.source_content_ref IS '源正文引用(本地相对路径或对象键)';
COMMENT ON COLUMN ia_agent_workspace_migration_item.source_payload IS '源正文快照(数据库后端)';
COMMENT ON COLUMN ia_agent_workspace_migration_item.target_backend_type IS '目标后端类型';
COMMENT ON COLUMN ia_agent_workspace_migration_item.target_storage_config_id IS '目标对象存储配置 ID';
COMMENT ON COLUMN ia_agent_workspace_migration_item.target_local_path IS '目标本地存储根目录';
COMMENT ON COLUMN ia_agent_workspace_migration_item.target_content_ref IS '目标正文引用';
COMMENT ON COLUMN ia_agent_workspace_migration_item.target_payload IS '目标正文快照';
COMMENT ON COLUMN ia_agent_workspace_migration_item.content_sha256 IS '正文 SHA-256(校验一致)';
COMMENT ON COLUMN ia_agent_workspace_migration_item.content_size IS '正文字节数';
COMMENT ON COLUMN ia_agent_workspace_migration_item.status IS '明细状态:copied/verified/failed';
COMMENT ON COLUMN ia_agent_workspace_migration_item.deleted IS '逻辑删除标志';
COMMENT ON COLUMN ia_agent_workspace_migration_item.create_time IS '创建时间';
COMMENT ON COLUMN ia_agent_workspace_migration_item.update_time IS '更新时间';
