-- =====================================================================
-- InnerAgent V5:存储配置表(P1 遗留台账④)
-- 移植自融光 ai-fusion-video 迁移(列定义逐一对照):
--   * B1.1.0.0.8__baseline_1.0.0.sql 的 afv_storage_config(基线全列)
--   * V1.0.6.1.2__storage_provider_profiles.sql(provider / options 两列,
--     基线与增量在此合并为最终形态)
-- 改造规则(与 V2/V3 一致):
--   * MySQL 8 -> PostgreSQL 17 方言;afv_ 前缀 -> ia_ 前缀;增加
--     app_id BIGINT NOT NULL DEFAULT 1(所属应用;单应用部署固定为 1,
--     P1 接入 AppContext 后显式写入;实体未映射该列,依赖默认值)。
--   * tinyint(0/1) -> BOOLEAN;json -> JSONB(JsonbTypeHandler 以字符串
--     写入,连接串需 stringtype=unspecified);datetime -> TIMESTAMP(3)。
--   * 工作区对象存储模式(ia_agent_workspace_config.storage_config_id,
--     V3)经 StorageConfigService 从本表加载配置,本表补齐后该链路可用。
-- =====================================================================

CREATE TABLE ia_storage_config (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id        BIGINT       NOT NULL DEFAULT 1,
    name          VARCHAR(128) NOT NULL,
    type          VARCHAR(32)  NOT NULL,
    provider      VARCHAR(32),
    endpoint      VARCHAR(512),
    bucket_name   VARCHAR(128),
    access_key    VARCHAR(256),
    secret_key    VARCHAR(256),
    region        VARCHAR(64),
    base_path     VARCHAR(256),
    custom_domain VARCHAR(512),
    options       JSONB,
    is_default    BOOLEAN      NOT NULL DEFAULT FALSE,
    status        INT          NOT NULL DEFAULT 1,
    remark        VARCHAR(1024),
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    create_time   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ia_storage_config IS '存储配置表(文件存储后端配置,支持本地与 S3 兼容对象存储)';
COMMENT ON COLUMN ia_storage_config.id IS '主键ID(ia_agent_workspace_config.storage_config_id 指向)';
COMMENT ON COLUMN ia_storage_config.app_id IS '所属应用;单应用部署固定为 1(P1 接入 AppContext 后显式写入)';
COMMENT ON COLUMN ia_storage_config.name IS '配置名称';
COMMENT ON COLUMN ia_storage_config.type IS '存储类型:local / s3(历史 aliyun_oss、tencent_cos 归一为 s3 + provider)';
COMMENT ON COLUMN ia_storage_config.provider IS 'S3 兼容厂商:generic_s3/aliyun_oss/tencent_cos/qiniu_kodo/ctyun_zos/minio';
COMMENT ON COLUMN ia_storage_config.endpoint IS 'OSS 端点地址';
COMMENT ON COLUMN ia_storage_config.bucket_name IS 'OSS 存储桶名称';
COMMENT ON COLUMN ia_storage_config.access_key IS 'OSS Access Key';
COMMENT ON COLUMN ia_storage_config.secret_key IS 'OSS Secret Key';
COMMENT ON COLUMN ia_storage_config.region IS '区域';
COMMENT ON COLUMN ia_storage_config.base_path IS '存储根路径(本地为磁盘路径,OSS 为 key 前缀)';
COMMENT ON COLUMN ia_storage_config.custom_domain IS '自定义域名(CDN 域名等)';
COMMENT ON COLUMN ia_storage_config.options IS '厂商扩展配置 JSON(pathStyleAccessEnabled / signingRegion 等)';
COMMENT ON COLUMN ia_storage_config.is_default IS '是否为默认存储配置(全局唯一,服务层写时互斥)';
COMMENT ON COLUMN ia_storage_config.status IS '状态:0-禁用 1-启用';
COMMENT ON COLUMN ia_storage_config.remark IS '备注';
COMMENT ON COLUMN ia_storage_config.deleted IS '逻辑删除标志';
COMMENT ON COLUMN ia_storage_config.create_time IS '创建时间';
COMMENT ON COLUMN ia_storage_config.update_time IS '更新时间';
