-- =====================================================================
-- InnerAgent V6:工具中枢补强(P1-T2a,02-技术方案 §4.3/§5.1、04-调研 V14/V18/V22)
-- 内容:
--   * ia_tool_registry:+工具版本、活刷新分诊(V14)待重新确认标记与暂存列。
--   * ia_tool_grant:+授权生命周期列(自动失效区别于主动撤销,V18)、决策记录;
--     conversation_id BIGINT -> VARCHAR(64)(对齐 ia_agent_conversation.conversation_id
--     的 UUID 语义,V2 建列时误用 BIGINT,本库尚无会话级授权数据,直接改型)。
--   * ia_audit_log:conversation_id BIGINT -> VARCHAR(64)(同上,会话 UUID 语义)。
--   * 新增 ia_tool_schema_history:schema 指纹变更历史留痕(分诊结果可追溯)。
-- 说明:
--   * ia_audit_log.decision_source 已由 V2 建列,V22 无需再迁移。
--   * V5 已被并行任务(ia_storage_config)预留,本任务从 V6 起编号。
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. ia_tool_registry:活刷新分诊(V14)与版本列
-- ---------------------------------------------------------------------
ALTER TABLE ia_tool_registry
    ADD COLUMN tool_version            VARCHAR(64),
    ADD COLUMN revalidate_required     BOOLEAN   NOT NULL DEFAULT FALSE,
    ADD COLUMN pending_schema          TEXT,
    ADD COLUMN pending_annotations_json TEXT,
    ADD COLUMN pending_schema_sha256   CHAR(64),
    ADD COLUMN pending_refresh_at      TIMESTAMP;

COMMENT ON COLUMN ia_tool_registry.tool_version IS '工具版本/来源版本号(宿主上报,可空)';
COMMENT ON COLUMN ia_tool_registry.revalidate_required IS '活刷新分诊(V14):存在安全相关差异待重新确认时为 TRUE,旧 schema 继续生效';
COMMENT ON COLUMN ia_tool_registry.pending_schema IS 'BREAKING 分诊暂存的新 schema(重新确认通过后生效)';
COMMENT ON COLUMN ia_tool_registry.pending_annotations_json IS 'BREAKING 分诊暂存的新注解 JSON(与 pending_schema 配套)';
COMMENT ON COLUMN ia_tool_registry.pending_schema_sha256 IS 'BREAKING 分诊暂存新 schema 的 SHA-256 指纹';
COMMENT ON COLUMN ia_tool_registry.pending_refresh_at IS '暂存写入时间';

-- ---------------------------------------------------------------------
-- 2. ia_tool_grant:授权生命周期(V18)与决策记录
-- ---------------------------------------------------------------------
ALTER TABLE ia_tool_grant
    ALTER COLUMN conversation_id TYPE VARCHAR(64) USING conversation_id::VARCHAR,
    ADD COLUMN invalidated        BOOLEAN      NOT NULL DEFAULT FALSE,
    ADD COLUMN invalidated_reason VARCHAR(64),
    ADD COLUMN decision_note      VARCHAR(512);

COMMENT ON COLUMN ia_tool_grant.conversation_id IS '会话ID(ia_agent_conversation.conversation_id,UUID;scope=permanent 时为 NULL)';
COMMENT ON COLUMN ia_tool_grant.invalidated IS '是否已自动失效(风险升级/安全 schema 变更/工具停用注销);与 deleted(主动撤销)区分';
COMMENT ON COLUMN ia_tool_grant.invalidated_reason IS '自动失效原因:risk_upgrade/schema_breaking/tool_disabled/tool_deleted';
COMMENT ON COLUMN ia_tool_grant.decision_note IS '授予决策记录(操作说明/来源上下文)';

-- ---------------------------------------------------------------------
-- 3. ia_audit_log:conversation_id BIGINT -> VARCHAR(64)
--    (对齐 ia_agent_conversation.conversation_id 的 UUID 语义;
--     表尚无业务数据,确认流/授权审计(T2b/本任务)需要携带会话 UUID)
-- ---------------------------------------------------------------------
ALTER TABLE ia_audit_log
    ALTER COLUMN conversation_id TYPE VARCHAR(64) USING conversation_id::VARCHAR;

COMMENT ON COLUMN ia_audit_log.conversation_id IS '会话ID(ia_agent_conversation.conversation_id,UUID)';

-- ---------------------------------------------------------------------
-- 4. ia_tool_schema_history:schema 指纹变更历史(新增;留痕+分诊审计)
-- ---------------------------------------------------------------------
CREATE TABLE ia_tool_schema_history (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id           BIGINT       NOT NULL DEFAULT 1,
    tool_id          BIGINT       NOT NULL,
    fqn              VARCHAR(200) NOT NULL,
    previous_sha256  CHAR(64),
    new_sha256       CHAR(64)     NOT NULL,
    triage           VARCHAR(16)  NOT NULL,
    outcome          VARCHAR(24)  NOT NULL,
    actor            VARCHAR(64),
    detail           TEXT,
    create_time      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ia_tool_schema_history_app_fqn
    ON ia_tool_schema_history (app_id, fqn, id);

COMMENT ON TABLE ia_tool_schema_history IS '工具 schema 指纹变更历史(活刷新分诊留痕,仅追加)';
COMMENT ON COLUMN ia_tool_schema_history.id IS '主键ID';
COMMENT ON COLUMN ia_tool_schema_history.app_id IS '所属应用;单应用部署固定为 1';
COMMENT ON COLUMN ia_tool_schema_history.tool_id IS '工具ID(ia_tool_registry.id)';
COMMENT ON COLUMN ia_tool_schema_history.fqn IS '工具全限定名';
COMMENT ON COLUMN ia_tool_schema_history.previous_sha256 IS '变更前 schema SHA-256(首次注册为 NULL)';
COMMENT ON COLUMN ia_tool_schema_history.new_sha256 IS '变更后 schema SHA-256';
COMMENT ON COLUMN ia_tool_schema_history.triage IS '分诊结论:unchanged-未变更 compatible-兼容变更 breaking-安全相关差异';
COMMENT ON COLUMN ia_tool_schema_history.outcome IS '处理结果:silent_refresh-静默刷新 applied-已生效 pending_review-转待审核 rejected-已拒绝';
COMMENT ON COLUMN ia_tool_schema_history.actor IS '操作者(admin:密钥指纹/系统)';
COMMENT ON COLUMN ia_tool_schema_history.detail IS '差异明细(分诊理由列表 JSON)';
COMMENT ON COLUMN ia_tool_schema_history.create_time IS '创建时间(仅追加)';
