-- =====================================================================
-- V7:对话附件表(ia_agent_attachment)
-- ---------------------------------------------------------------------
-- 02-技术方案 §7.1(ADR-T4):POST /ia/api/v1/attachments(P1-T3b)。
-- 附件正文复用智能体工作空间三后端链路(database/local/object_storage,
-- 后端定位与 ia_storage_config 加载同 ia_agent_workspace_config,P1 台账④);
-- 本表仅登记附件元数据与正文定位(content_ref/payload),不重复存正文:
--   * backend_type=database       -> payload 列存 Base64 正文(TEXT 兼容二进制);
--   * backend_type=local          -> content_ref 为本地相对路径;
--   * backend_type=object_storage -> content_ref 为对象键,storage_config_id 指向
--     ia_storage_config(P1 台账④链路)。
-- 顺带:P0 演示 mock 模型(V4)补多模态能力配置,使演示部署可走附件上传
-- (仅 demo 数据,生产模型能力由管理面配置)。
-- =====================================================================

CREATE TABLE ia_agent_attachment (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id            BIGINT       NOT NULL DEFAULT 1,
    tenant_id         BIGINT       NOT NULL DEFAULT 0,
    user_id           BIGINT       NOT NULL,
    model_id          BIGINT,
    file_name         VARCHAR(512),
    mime_type         VARCHAR(128) NOT NULL,
    input_type        VARCHAR(16)  NOT NULL,
    transport         VARCHAR(16)  NOT NULL,
    size_bytes        BIGINT       NOT NULL,
    backend_type      VARCHAR(32)  NOT NULL,
    storage_config_id BIGINT,
    local_path        VARCHAR(512),
    content_ref       VARCHAR(1024),
    content_sha256    CHAR(64)     NOT NULL,
    payload           TEXT,
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    create_time       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ia_agent_attachment_user
    ON ia_agent_attachment (app_id, user_id, id);

COMMENT ON TABLE ia_agent_attachment IS '对话附件表(POST /ia/api/v1/attachments 上传登记)';
COMMENT ON COLUMN ia_agent_attachment.id IS '主键ID(resourceUrl 引用 /ia/api/v1/attachments/{id})';
COMMENT ON COLUMN ia_agent_attachment.app_id IS '所属应用;单应用部署固定为 1(拦截器显式写入)';
COMMENT ON COLUMN ia_agent_attachment.tenant_id IS '所属租户(团队)ID';
COMMENT ON COLUMN ia_agent_attachment.user_id IS '上传用户 ID';
COMMENT ON COLUMN ia_agent_attachment.model_id IS '能力校验所用对话模型 ID(ia_ai_model.id)';
COMMENT ON COLUMN ia_agent_attachment.file_name IS '原始文件名';
COMMENT ON COLUMN ia_agent_attachment.mime_type IS 'MIME 类型(规范化小写,去参数)';
COMMENT ON COLUMN ia_agent_attachment.input_type IS '输入类型:image/video/audio/file(按 MIME 推导)';
COMMENT ON COLUMN ia_agent_attachment.transport IS '请求传输方式:url/base64(须在模型能力白名单内)';
COMMENT ON COLUMN ia_agent_attachment.size_bytes IS '正文字节数';
COMMENT ON COLUMN ia_agent_attachment.backend_type IS '正文所在后端:database/local/object_storage(随工作空间配置)';
COMMENT ON COLUMN ia_agent_attachment.storage_config_id IS '正文所在对象存储配置 ID(ia_storage_config.id)';
COMMENT ON COLUMN ia_agent_attachment.local_path IS '正文所在本地存储根目录';
COMMENT ON COLUMN ia_agent_attachment.content_ref IS '本地相对路径或对象键(database 后端为空)';
COMMENT ON COLUMN ia_agent_attachment.content_sha256 IS '正文 SHA-256';
COMMENT ON COLUMN ia_agent_attachment.payload IS 'database 后端正文(Base64);local/object_storage 后端为空';
COMMENT ON COLUMN ia_agent_attachment.deleted IS '逻辑删除标志';
COMMENT ON COLUMN ia_agent_attachment.create_time IS '创建时间';
COMMENT ON COLUMN ia_agent_attachment.update_time IS '更新时间';

-- ---------------------------------------------------------------------
-- 演示数据:P0 mock 模型(V4__demo_seed.sql)补多模态能力,附件上传可演示
-- ---------------------------------------------------------------------
UPDATE ia_ai_model
SET multimodal_input_types      = '["image","file"]'::jsonb,
    multimodal_input_transports = '{"image":["url","base64"],"file":["url","base64"]}'::jsonb,
    support_vision              = TRUE
WHERE code = 'mock-text';
