import type { DocLocaleContent } from './types'

/**
 * 文档中心中文内容(内化自 docs/接入指南.md,按官网文档形态改写;
 * 端口基准:InnerAgent server 18090、宿主后端 9300)。
 */
const zhCN: DocLocaleContent = [
  {
    id: 'quickstart',
    title: '快速开始',
    summary: '三步从零到可用对话:引依赖 → 桥配置 → 前端嵌入。',
    next: 'app-registration',
    blocks: [
      { type: 'p', text: '前置条件:InnerAgent server 已部署(示例端口 18090);宿主为 Spring Boot Servlet Web 应用(Java 21)。走完本页三步,即可在宿主页面里用自然语言操控应用。' },
      { type: 'h', text: '① 引依赖 + 写工具' },
      { type: 'code', lang: 'xml', code: '<dependency>\n  <groupId>com.inneragent</groupId>\n  <artifactId>inneragent-spring-boot-starter</artifactId>\n  <version>0.1.0-SNAPSHOT</version>\n</dependency>' },
      { type: 'p', text: 'starter 经自动装配引入 /ia-mcp 桥与 X-IA-Act 验签(条件:Servlet Web 应用且 inneragent.bridge.enabled=true,默认 true),宿主无需任何 @EnableXxx 注解。业务能力以 @IaTool 注解暴露成 MCP 工具,写法见「工具桥」章节。' },
      { type: 'callout', tone: 'warn', text: '工具方法参数名依赖 -parameters 编译参数;宿主自己的模块若未开启,请一律显式写 @IaToolParam(value="..."),缺参即抛「参数名不可得」。' },
      { type: 'h', text: '② 桥配置(yaml 最小集)' },
      { type: 'code', lang: 'yaml', code: 'inneragent:\n  bridge:\n    # InnerAgent 主服务地址(宿主从这里拉 JWKS 验 act token)\n    server-base: http://localhost:18090\n    act:\n      # 最关键的一行:必须与注册到管理面的 endpoint_url 完全一致\n      audiences:\n        - http://localhost:18091/ia-mcp' },
      { type: 'p', text: 'act.audiences 是默认占位值,不改即错。InnerAgent 按注册表的 endpoint_url 签发 act token 的 aud,宿主桥做精确匹配,错配即 /ia-mcp 全量 401(fail-closed)。排障口诀:先对齐「yaml audiences = 管理面 endpoint_url」,再查别的。' },
      { type: 'h', text: '③ 前端嵌入' },
      { type: 'code', lang: 'js', code: "const sdk = await import('/js/inneragent-chat.js')\n\nsdk.init({\n  appKey: 'my-host-app',         // 与管理面注册的 appKey 一致\n  baseURL: '/ia/api/v1',         // 跨域部署时配绝对地址\n  agentType: 'my_agent',\n  tokenGetter: async () => {     // 缓存 + 临期重签,支持被反复调用\n    const res = await fetch('/host/api/embed-token', { credentials: 'include' })\n    return res.ok ? res.text() : null\n  },\n})\nsdk.registerInnerAgentChat()     // 注册 <inneragent-chat>(幂等)" },
      { type: 'p', text: 'tokenGetter 的完整契约(懒加载、401 重取、null 语义)见「前端嵌入」章节;嵌入完成后再回到管理面完成「应用开通与公钥登记」,整个链路即闭环。' },
    ],
  },
  {
    id: 'app-registration',
    title: '应用开通与公钥登记',
    summary: '管理面注册应用、登记 RSA 公钥与工具条目;一次开通,运行期不依赖。',
    next: 'embed-token',
    blocks: [
      { type: 'p', text: '管理面鉴权双轨:自动化/脚本用请求头 X-IA-Admin-Key(即服务端 IA_ADMIN_KEY 环境变量,未配置时管理面整体 403 默认关闭);人工走管理员登录会话。本页用密钥头示例。' },
      { type: 'h', text: '注册应用(登记 RSA 公钥)' },
      { type: 'code', lang: 'bash', code: '# 生成宿主签名密钥对(私钥留在宿主,公钥登记)\nopenssl genrsa 2048 | openssl rsa -pubout\n\ncurl -s -X POST "http://localhost:18090/ia/api/v1/admin/apps" \\\n  -H "X-IA-Admin-Key: ${IA_ADMIN_KEY}" -H \'Content-Type: application/json\' -d \'{\n    "appKey": "my-host-app",\n    "name": "ACME Demo App",\n    "signPublicKey": "-----BEGIN PUBLIC KEY-----\\n...\\n-----END PUBLIC KEY-----",\n    "webhookUrl": "https://host.example.com/ia/webhook",\n    "webhookSecret": "whsec-9f2c1ab77d"\n  }\'' },
      { type: 'list', items: [
        'signPublicKey 只接受 RSA 公钥 PEM,非法 PEM → 400;appKey 重复 → 409。',
        '响应 data.signKeyFingerprint(SHA-256 十六进制前 16 位)用于核对密钥配对。',
        'webhook 可在注册时给,也可后续经 PUT /ia/api/v1/admin/webhooks/config 配置。',
      ] },
      { type: 'h', text: '注册工具(宿主桥不主动推送)' },
      { type: 'p', text: 'starter 启动时把 @IaTool 注册进宿主进程内的 MCP server;InnerAgent 通过对 endpoint_url 周期性 tools/list 指纹轮询感知清单。注册表条目由宿主方经管理面 API 写入:' },
      { type: 'code', lang: 'bash', code: 'curl -s -X POST "http://localhost:18090/ia/api/v1/admin/tools" \\\n  -H "X-IA-Admin-Key: ${IA_ADMIN_KEY}" -H \'Content-Type: application/json\' -d \'{\n  "serverKey": "my-host-app",\n  "toolName": "get_customer",\n  "description": "Look up customer info by ID",\n  "riskLevel": "low",\n  "source": "host_app",\n  "endpointUrl": "http://localhost:18091/ia-mcp",\n  "parametersSchema": "{\\"type\\":\\"object\\",\\"properties\\":{\\"customer_id\\":{\\"type\\":\\"string\\"}},\\"required\\":[\\"customer_id\\"]}"\n}\'' },
      { type: 'list', items: [
        'endpointUrl = 宿主桥地址,必须与 act.audiences 完全一致。',
        'serverKey 仅允许字母/数字/连字符(禁下划线);source 取 host_app 或 third_party。',
        '模型可见名为确定性 FQN:mcp__<serverKey>__<toolName>。',
        'riskLevel 词表是 low/medium/high(starter 注解词表 READ/WRITE/DESTRUCTIVE 仅用于工具方法)。',
      ] },
      { type: 'callout', tone: 'info', text: '写工具免确认的授权日常由用户在确认卡产生(本次/本会话/总是/拒绝);管理员也可经 POST /ia/api/v1/admin/grants 预授(scope = permanent | conversation)。' },
    ],
  },
  {
    id: 'embed-token',
    title: 'embed token',
    summary: '宿主私钥签发的用户令牌:claims 表、生命周期与轮换宽限。',
    next: 'frontend-embed',
    blocks: [
      { type: 'p', text: 'embed token 由宿主后端 RS256 签名(私钥不出宿主),前端 SDK 携带它访问 InnerAgent。必需 claims 为 iss / sub / exp:' },
      { type: 'table', head: ['claim', '必填', '说明'], rows: [
        ['iss', '是', '应用标识 appKey,服务端据此定位应用行'],
        ['sub', '是', '终端用户 ID(数字串),来自宿主用户体系'],
        ['exp', '是', '过期时间,宿主自定;服务端建议 12h'],
        ['tenantId', '否', '租户 ID(可选)'],
        ['aud', '—', '无此 claim;算法强校验 RS256'],
      ] },
      { type: 'h', text: '生命周期时序(SDK 背后)' },
      { type: 'list', items: [
        'SDK 在每次 HTTP 请求与每次 SSE 连接前调用 tokenGetter —— 回调内部应缓存并在临期时重签,避免每请求打宿主接口。',
        '收到 401 时 SDK 会再次调用 tokenGetter 并用新 token 重试恰好一次;并发 401 经单飞合并为一次重取。',
        'tokenGetter 返回 null 表示宿主明确给不出 token:SDK 不重试,按 401 抛错(不要用抛异常表达「无 token」)。',
      ] },
      { type: 'h', text: '签发端点示例(nimbus-jose-jwt 骨架)' },
      { type: 'code', lang: 'java', code: '@GetMapping("/host/api/embed-token")\npublic String token() throws JOSEException {\n    long now = System.currentTimeMillis() / 1000;\n    JWTClaimsSet claims = new JWTClaimsSet.Builder()\n            .issuer("my-host-app")          // iss = appKey\n            .subject("10086")               // sub = 宿主用户 ID(数字串)\n            .claim("tenantId", 1L)          // 可选\n            .issueTime(new Date(now * 1000))\n            .expirationTime(new Date((now + 12 * 3600) * 1000)) // 建议 12h\n            .build();\n    SignedJWT jwt = new SignedJWT(new JWSHeader.Builder(JWSAlgorithm.RS256).build(), claims);\n    jwt.sign(new RSASSASigner(privateKey)); // 与登记 signPublicKey 配对\n    return jwt.serialize();\n}' },
      { type: 'h', text: '公钥轮换与 72h 双钥宽限' },
      { type: 'p', text: '管理面提交不同的 signPublicKey 即触发轮换:旧公钥移入宽限区(embed-key-grace,默认 72h,可配 30m/7d 等,配 0 关闭)。宽限期内旧钥签发的存量 token 仍验签通过——宿主在窗口内完成换签,存量用户不会被立即全量下线。' },
    ],
  },
  {
    id: 'frontend-embed',
    title: '前端嵌入',
    summary: 'WC 直挂(推荐)与 iframe postMessage 两种模式,token 永不进 URL。',
    next: 'tool-bridge',
    blocks: [
      { type: 'h', text: '模式一:Web Component 直挂(推荐)' },
      { type: 'code', lang: 'html', code: '<inneragent-chat id="chat" view="chat"></inneragent-chat>\n<style> inneragent-chat { display: block; height: 560px; } </style>\n<script type="module">\n  const sdk = await import(\'/js/inneragent-chat.js\')\n\n  sdk.init({\n    appKey: \'my-host-app\',\n    baseURL: \'/ia/api/v1\',            // 默认值;跨域部署时配绝对地址\n    agentType: \'my_agent\',\n    tokenGetter: async () => {\n      const res = await fetch(\'/host/api/embed-token\', { credentials: \'include\' })\n      if (!res.ok) return null         // 拿不到 → SDK 不重试,按 401 抛错\n      return res.text()\n    },\n    // theme: { \'--ia-primary\': \'#0ea5e9\' },  // 可选:主题令牌\n  })\n  sdk.registerInnerAgentChat()         // 注册 <inneragent-chat>(幂等)\n<\/script>' },
      { type: 'list', items: [
        '懒加载:每次请求/连接前都会调用 tokenGetter,回调内做缓存 + exp 临期重签。',
        '401 重取:SDK 用新 token 重试恰好一次,并发经单飞合并——回调必须支持被反复调用。',
        'null 语义:返回 null = 明确无 token,SDK 不重试。',
      ] },
      { type: 'h', text: '模式二:iframe postMessage' },
      { type: 'p', text: '被嵌页 src 只给页面地址、不带 token;握手(origin 校验)完成后,token 经消息桥下发。适合需要更强隔离边界的宿主。' },
      { type: 'code', lang: 'js', code: "import { createIframeEmbed } from '/js/iframe-host.js'\n\nconst embed = createIframeEmbed({\n  src: 'https://host.example.com/ia/frame.html', // src 无 token\n  appKey: 'my-host-app',\n  tokenGetter: async () => fetch('/host/api/embed-token').then(r => r.text()),\n  container: document.getElementById('chat'),\n})\nawait embed.ready   // 握手完成(origin 校验通过)后 resolve" },
      { type: 'callout', tone: 'warn', text: '生产环境建议给 iframe 加显式 sandbox,并按部署域配置 origin allowlist 与 CSP。' },
    ],
  },
  {
    id: 'tool-bridge',
    title: '工具桥',
    summary: '@IaTool 注解、风险级与确认行为、桥配置开关全集。',
    next: 'webhook',
    blocks: [
      { type: 'h', text: '@IaTool / @IaToolParam' },
      { type: 'table', head: ['注解属性', '说明', '缺省'], rows: [
        ['@IaTool.name', 'MCP 工具名(桥内唯一)', '方法名'],
        ['@IaTool.description', '模型可见描述', '工具名'],
        ['@IaTool.riskLevel', 'READ / WRITE / DESTRUCTIVE', 'WRITE'],
        ['@IaToolParam.value', '参数名', '反射参数名(需 -parameters)'],
        ['@IaToolParam.description', '参数描述(进 schema)', '无'],
        ['@IaToolParam.required', '是否进 schema required', 'true(保守默认)'],
      ] },
      { type: 'h', text: '一读一写示例' },
      { type: 'code', lang: 'java', code: '@Component\npublic class CrmTools {\n\n    /** READ → DEFAULT 档位自动执行、不打扰用户 */\n    @IaTool(name = "get_customer",\n            description = "Look up customer info by ID",\n            riskLevel = ToolRiskLevel.READ)\n    public Map<String, Object> getCustomer(\n            @IaToolParam(value = "customer_id") String customerId,\n            IaActClaims claims) {                    // 尾参注入 act 身份(可省)\n        ...\n    }\n\n    /** WRITE → DEFAULT 档位先确认后执行;批准时可勾「总是允许」 */\n    @IaTool(name = "update_customer_level",\n            description = "Update customer level (normal/silver/gold)",\n            riskLevel = ToolRiskLevel.WRITE)\n    public Map<String, Object> updateCustomerLevel(\n            @IaToolParam(value = "customer_id") String customerId,\n            @IaToolParam(value = "level") String level,\n            IaActClaims claims) {\n        ... // 宿主侧做最终权限校验(行级),见「安全责任划分」\n    }\n}' },
      { type: 'list', items: [
        'READ → readOnlyHint=true,DEFAULT 档自动执行;WRITE → 先确认后执行,确认卡四档:本次/本会话/总是/拒绝。',
        'DESTRUCTIVE → destructiveHint=true,注册时强制高风险,一律确认。',
        '返回 Map 原样进 structuredContent;抛任意异常 → isError=true + {"status":"error"} 回灌模型,运行不终止。',
      ] },
      { type: 'h', text: '桥配置与开关(灰度)' },
      { type: 'table', head: ['配置键', '缺省', '说明'], rows: [
        ['inneragent.bridge.enabled', 'true', 'false = 不装配桥(一键关闭)'],
        ['inneragent.bridge.server-base', '无', '主服务地址;缺省时 /ia-mcp 因 JWKS 不可达全量 401'],
        ['inneragent.bridge.endpoint', '/ia-mcp', '宿主桥 MCP 端点路径'],
        ['inneragent.bridge.tool-packages', '空', '非 bean 工具类的扫描包'],
        ['inneragent.bridge.scan.fail-fast', 'true', '工具重名/schema 失败是否阻断启动'],
        ['inneragent.bridge.act.audiences', '[ia-mcp](占位)', '期望 aud,必须改为真实地址并与 endpointUrl 一致'],
        ['inneragent.bridge.act.cache-ttl', '5m', 'JWKS 周期刷新'],
        ['inneragent.bridge.act.key-retention', '72h', '消失密钥的本地保留期(轮换宽限)'],
      ] },
      { type: 'callout', tone: 'warn', text: '排障口诀:先对齐「yaml act.audiences = 管理面注册的 endpoint_url」,再查别的;错配统一 401 invalid_act_token,不区分失败细节。' },
    ],
  },
  {
    id: 'webhook',
    title: 'Webhook',
    summary: '运行终态回调:订阅事件、HMAC 验签要点与重试语义。',
    next: 'security',
    blocks: [
      { type: 'p', text: '可订阅事件:run.finished / run.failed / run.cancelled。非 2xx 按 1m → 5m → 30m → 2h → 12h 退避,最多 5 次(含首投);EXHAUSTED 后只能人工重投。载荷形如 {event, appId, runId, status, finishedAt, errorCode?, errorMessage?}。' },
      { type: 'h', text: '验签要点' },
      { type: 'list', items: [
        '请求头四个:X-IA-Signature、X-IA-Timestamp(epoch 毫秒)、X-IA-Nonce、X-IA-Delivery(宿主幂等去重键)。',
        '签名为 HMAC-SHA256(secret, "timestamp.nonce.body") 小写十六进制;按原始字节(raw body)重算比对,不要先反序列化。',
        '按 X-IA-Delivery 幂等去重;校验 timestamp 时间窗防重放。',
        '验签失败快回非 2xx;secret 未配置时统一 503(运维问题不尝试验签)。',
      ] },
      { type: 'code', lang: 'js', code: "import crypto from 'node:crypto'\n\nconst expected = crypto.createHmac('sha256', webhookSecret)\n  .update(`${timestamp}.${nonce}.${rawBody}`)\n  .digest('hex')\nif (expected !== signature) return res.status(401).end()\n\nif (await seenBefore(deliveryId)) return res.status(200).end()  // 幂等去重\nawait handleEvent(JSON.parse(rawBody))\nres.status(200).end()                                           // 快回 2xx" },
      { type: 'callout', tone: 'info', text: '连通性验证:管理面 POST /ia/api/v1/admin/webhooks/config/test 会真实签名单发,返回 {ok, signatureValid, httpStatus}。' },
    ],
  },
  {
    id: 'security',
    title: '安全责任划分',
    summary: '平台与宿主各自守护什么;生产上线前的安全清单。',
    next: 'endpoints',
    blocks: [
      { type: 'table', head: ['维度', '宿主(你)', 'InnerAgent'], rows: [
        ['签名密钥', 'RSA 私钥自持,私钥不出宿主', '只存公钥;轮换 72h 双钥宽限'],
        ['用户身份', 'embed token 只签给已认证用户', 'RS256 强校验验签;act token 60s 内环'],
        ['越权拦截', '工具方法内按 IaActClaims.userId 做行级校验', '只传递与呈现约束范围(resolve_scope)'],
        ['写操作确认', '实现 resolve_scope 可免体验降级', '未实现时写操作强制 ASK,授权不可绕过'],
        ['审计', '工具侧自证合规', '仅追加审计 + 读时按键名脱敏 + decision_source'],
      ] },
      { type: 'p', text: '约束范围(resolve_scope)是宿主契约:宿主在工具集中实现同名工具即视为「已实现」;四个返回数组宽进(缺字段按空容忍)——宿主是协议的最终裁决方。未实现不危险,但写操作每次都要确认(scopeDegraded)。' },
      { type: 'h', text: '生产上线清单' },
      { type: 'list', items: [
        '关闭 allow-anonymous-demo(生产严禁开启)。',
        '注入 IA_ADMIN_KEY / IA_ADMIN_SESSION_SECRET / IA_ACT_KEY_PEM(act 密钥缺省临时生成,重启即换)。',
        '删除 mock 模型配置;act.audiences 与 endpoint_url 对齐。',
        'iframe 模式:显式 sandbox + 按部署域配置 allowedOrigins 与 CSP。',
        'webhook secret 已配置,验签代码按原始字节比对并做幂等。',
        '附件:base64 ≤ 10MB 开箱即用;url 传输要求模型提供方能 GET 到 InnerAgent API(部署前置条件)。',
      ] },
    ],
  },
  {
    id: 'endpoints',
    title: '端点速查',
    summary: '本 Demo 宿主后端与 InnerAgent server 的常用端点一览。',
    next: null,
    blocks: [
      { type: 'p', text: '端口基准:InnerAgent server 18090、本 Demo 宿主后端 9300。前端开发模式下 /api 代理到 :9300、/ia 代理到 :18090。' },
      { type: 'table', head: ['方法', '路径', '说明', '鉴权'], rows: [
        ['POST', '/api/demo/login', '演示登录(任意用户名),返回会话 token', '公开'],
        ['GET', '/api/ia/embed-token', '签发 embed token(RS256,iss=appKey、sub=用户 ID、exp 12h)', '演示会话'],
        ['GET', '/api/ia/server-status', '开通状态自检(registered/not_registered/unreachable/admin_key_missing)', '演示会话'],
        ['GET', '/api/demo/config', '公开配置(inneragentBaseUrl / appKey / agentType)', '公开'],
        ['POST', '/ia/api/v1/runs', '发起运行(SSE 流,请求体含 agentType)', 'embed token'],
        ['POST', '/ia/api/v1/runs/{runId}/confirm', '工具确认(decisions 按 toolCallId 批准/拒绝)', 'embed token'],
        ['GET', '/.well-known/jwks.json', 'act token JWKS(server 根路径,无 /ia 前缀)', '公开'],
        ['POST', '/ia-mcp', '宿主桥 MCP 端点(tools/list · tools/call,无状态)', 'X-IA-Act(60s)'],
        ['POST', '/ia/webhook', '运行终态回调(X-IA-Signature HMAC 验签)', 'HMAC'],
      ] },
      { type: 'callout', tone: 'info', text: '想亲手换一枚 embed token?打开 API 体验台,输入任意用户名即可完成「登录 → 签发 → claims 解码」全流程。' },
    ],
  },
]

export default zhCN
